- packages/cli/src/index.ts
- packages/contracts/hardhat.config.ts
- packages/hardhat-cannon/src/index.ts
- packages/hardhat-cannon/src/tasks/publish.ts
- packages/hardhat-cannon/src/type-extensions.ts
- packages/registry/hardhat.config.ts
- packages/sample-project/hardhat.config.ts
- packages/website/content/docs.md
- Main addition is the `--registry-address` option. Let's do a release after this is in.
- We're defaulting to the cloudflare rpc in the cli, so I switched it to this in the hardhat plug-in
- Wrote the deployments guide
- Removed `publisherPrivateKey`, doesn't seem to be used.
- Made the `anvil: ` part of the CLI output gray. It's still rendering twice sometimes, but didn't nail down why yet.
> Guides, etc.

- packages/builder/src/definition.test.ts
- packages/builder/src/definition.ts
Right now cannon has a check for extraneous dependencies. unfortunately,
when assembling layers for a cannon chart, it is possible that
it can accumulate extraenous deps within the layers even if the original
cannonfile was clean.
this process is very slow: in worst case, the algo is now cubic speed, (
though this isnt taking into account ridiculous cases). If the user
has a modern comture, the layer calculation should still be reasonably
fast, but we will want to be looking for ways to optimize this algorithm
in the future.
Keeping in the checks to prevent extraneous dependencies should help,
but we will probably need a system to track "newly" extraneous dependencies
so that the search can be much faster, if needed
> hotfix: eliminate extraneous layer deps

- packages/builder/src/steps/contract.ts
this is because the usecase for this is deploying transparent proxies and the impl
contract should be visible in the deployed contracts. Also, the contract
may be deployed/generated by a run step and therefore is not a known artifact.
> hotfix: shouldn't use artifacts to resolve abi for contract

- packages/builder/src/steps/invoke.ts
- packages/cli/src/helpers.ts
- packages/website/content/docs.md
if you have a contract which is generated and is not available in the
artifacts, it may be necessary to pull the ABI from a previously deployed
contract instead.
this could be a problem for etherscan verification because in this case cannon
doesn't technically have the source in order to verify the contract.
not sure about hte naming. Thoughts?
> add abiOf to `factory` on invoke

- packages/builder/src/util.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/run.ts
There's an error that happens when calling `ethers.utils.parseEther('10000')`, which returns `'0x021e19e0c9bab2400000'` which contains an extra leading `0` and makes it throw an error when using it for `hardhat_setBalance`.
This fix resolves that not relying on ethers to generate 10.000ETH in hex wei.
> fix default value given to hardhat_setBalances

- packages/hardhat-cannon/src/tasks/deploy.ts
If on the Hardhat config, no `accounts` value is setted, it is going to have the value `'remote'` by default, causing the privateKey to be passed as `'r'` and throwing an error. This fixes the bug only loading privateKeys if setted.
> Fix provider wrapping

- packages/builder/src/builder.ts
- packages/builder/src/steps/contract.ts
- packages/builder/src/steps/invoke.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/deploy.ts
these bugs are all very small and all had workarounds, so I can package them all here like this
* configuration for possibly nested properties (such as `args` for contacts) now converts to JSON before injecting template. This allows for us to inject anywhere in the data structure, or even to inject entirely new json structures perhaps
* topology error--did not carry over taints between leaves
* returned provider from the cli does not include the latest set of artifacts after build is completed
> misc bugs found while using cannon with legacymarket

- packages/builder/src/steps/invoke.ts
- packages/builder/src/util.ts
This PR fixes the option to set custom `abi =` when using a contract as `target =` instead of an address during `invoke` steps.
> Fix custom abi usage on invoke steps

- packages/builder/src/steps/contract.ts
- packages/builder/src/steps/invoke.ts
- packages/builder/src/steps/run.ts
- packages/builder/src/types.ts
- packages/builder/src/util.ts
- packages/cli/src/commands/inspect.ts
for "diamond" style proxies which have multiple implementations behind the main, it is required to supply an array for `abiOf` instaed of a single target.
Additionally, (this is extremely minor, but) it should be possible to specify the `from` address on the `contract` step
> need ability to use `abiOf` with an array of previous contracts

- packages/builder/src/builder.ts
- packages/builder/src/constants.ts
- packages/builder/src/index.ts
- packages/builder/src/util.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/helpers.ts
- packages/cli/src/rpc.ts
- packages/cli/src/types.ts
- packages/hardhat-cannon/src/index.ts
- packages/hardhat-cannon/src/internal/load-cannonfile.ts
- packages/hardhat-cannon/src/tasks/deploy.ts
also changes `getArtifacts` behavior a bit to attempt to load the artifact, and if fail, load from cannon artifact cache for hardhat
> add a dedicated chainid `13370` to cannon network

- packages/builder/src/builder.ts
during package upgrades, if a step has no changes in the check hash, the step will be skipped even if dependencies had changed. This is desirable behavior. However, if the context of a upstream dependency has changed, it is important for that change to be carried over to subsequent contexts.
We can accomplish this by simply overriding the previous context onto the new context. This is acceptable since context can only extended by subsequent steps (aka, not upgraded).
> fix isolated skip context not carried over

- packages/cli/src/commands/run.ts
- packages/cli/src/index.ts
This PR fixes several bugs that were on the CLI:
* There was a commands definition conflict having `npx cannon run` to be an alias when running only `npx cannon`. This caused to recognise other commands (e.g. `deploy`) as a param for `run`.
* ❗ The simple solution for this was to just remove the alias.❗
* Several params that needed a value were defined using `[ ... ]` on commander. All of these were changed to `< ... >`
* Fixes the `--cannon-directory` param on `cannon deploy`
> Fix params definition on CLI

- packages/builder/src/registry.ts
- packages/cli/src/commands/publish.ts
This PR fixes a bug when trying to publish a package without custom settings it wouldn't work, because ethers.js would think that the last `undefined` was an extra argument for the contract call.
> fix default overrides on registry publish

- packages/builder/src/registry.ts
- packages/builder/src/storage.ts
- packages/builder/src/types.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/index.ts
- packages/hardhat-cannon/src/tasks/build.ts
for upgradable/proxy protocols, allow for generation of deployments using a previous deployment as a base.
cannon will automatically detect any changes and only run deployment steps for those changes.
the deployment manifest file will contain a `upgradeFrom` option, allowing for a user to step back through the upgrade history for a package, which is pretty cool!
> add `--upgrade-from` option

- packages/builder/src/helpers/import-from.ts
- packages/builder/src/steps/run.ts
This PR adds the possibility of executing scripts on Run steps coming from an NPM dependency, e.g.:
```toml
[run.generate_router]
exec = "@synthetixio/core-router"
func = "generate"
args = ["contracts/routers/chain-<%= chainId %>/Router.sol:Router"]
```
> Add npm modules compatibility on run steps

- packages/builder/src/builder.ts
- packages/builder/src/index.ts
- packages/builder/src/steps/invoke.ts
- packages/builder/src/steps/keeper.ts
- packages/builder/src/steps/run.ts
- packages/builder/src/types.ts
- packages/builder/src/util.test.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/helpers.ts
- packages/cli/src/interact.ts
- packages/cli/src/util/printer.ts
- packages/hardhat-cannon/src/internal/load-cannonfile.ts
- packages/hardhat-cannon/src/subtasks/load-package-definition.ts
- packages/hardhat-cannon/src/tasks/deploy.ts
sometimes it is necessary to store values which are not addresses after executing an invoke statement.
a new data structure has been added to the cannon ctx to handle this called `extras`.
sorry if the name isn't great, I didn't want to say `outputs` or `misc` because both of those terms are used elsewhere, and in truth this functionality should be avoided unless it is really necessary for whatever cannon package you are building.
> add capability to write `extras` from invokes

- packages/builder/src/types.ts
- packages/cli/src/commands/inspect.ts
This PR adds all the nested contracts from the `imports` when writing deployments files. Creating a sub directory for each `provision.*` or `import.*` state.
> Add nested structures to write deployments

- packages/builder/src/actions.ts
- packages/builder/src/builder.ts
- packages/builder/src/definition.ts
- packages/builder/src/steps/provision.ts
while upgrading synthetix today we ran into some probs:
* its possible for some bad state to be carried over steps through `_.clone` instead of `_.cloneDeep`
* provision of partial deployments will not be run unless we actually check the status of the deployment
both these issues have been resolved with this PR, and tested against the observed cases to verify.
test commands:
```
npx cannon build omnibus-goerli.toml --upgrade-from synthetix-omnibus:3.0.0-alpha.8 --network https://goerli.infura.io/v3/$INFURA_KEY --dry-run
npx cannon build omnibus-optimism-goerli.toml --upgrade-from synthetix-omnibus:3.0.0-alpha.10 --network https://optimism-goerli.infura.io/v3/$INFURA_KEY --dry-run
npx cannon build omnibus-goerli.toml --upgrade-from synthetix-omnibus:3.0.0-alpha.10 --network …
```
> some issues with upgrades resolved

- package-lock.json
- packages/builder/jest.config.ts
- packages/builder/src/create2.test.ts
- packages/builder/src/definition.test.ts
- packages/builder/src/definition.ts
while building the uniswap pkg found this exciting error that occurs when layers are merged twice. Some of the old dependencies get detached, and you end up with this extra "island" of incomplete dependencies
> fix topology edge case

- lerna.json
- package-lock.json
- packages/hardhat-cannon/package-lock.json
- packages/hardhat-cannon/package.json
- packages/hardhat-cannon/src/tasks/build.ts
- packages/registry/package-lock.json
- packages/registry/package.json
- packages/sample-hardhat-project/package-lock.json
- packages/sample-hardhat-project/package.json
This PR fixes a bug on the hardhat-cannon package, that caused during build using the `--impersonate` param to not return all the hardhat signers.
> Fix usage of hardhat accounts during build when impersonating

- packages/builder/src/steps/contract.ts
linked libraries record should not be saved as part of getState result of contract
> fix bad state caused by contract.ts change

- packages/hardhat-cannon/src/tasks/build.ts
It does not make sense to configure --dry-run when using the `hardhat` network. If you would need to use create a fork using the hardhat network, it can be done on hardhat's config: https://hardhat.org/hardhat-network/docs/guides/forking-other-networks#forking-from-mainnet
> Add error throw when trying to use hardhat network with --dry-run

- packages/registry/contracts/CannonRegistry.sol
- packages/registry/contracts/EfficientStorage.sol
- packages/registry/test/contracts/CannonRegistry.test.ts
the owner of a package may grant a list of additional deployers. these deployers can publish to a package as if they are the owner.
this is useful if you want to have multiple parties deploying a package, and want to lower the security level of publishing a package (since deployers do not have permission to nominate a new owner)
> add capability to grant additional deployers

- packages/cli/src/index.ts
Untested. We do hardhat compile with the plug-in so I think it makes sense to add this here?
> run forge build when using cli

- packages/builder/package-lock.json
- packages/builder/src/builder.ts
- packages/builder/src/definition.ts
- packages/builder/src/steps/provision.ts
- packages/builder/src/types.ts
- packages/cli/package-lock.json
- packages/cli/src/commands/alter.ts
- packages/cli/src/commands/build.ts
- packages/hardhat-cannon/package-lock.json
- packages/sample-hardhat-project/cannonfile.consumer.toml
- packages/website/package-lock.json
in order to allow for settings to be interpolated with results from the package (or timestamp or etc), a "pre" context is required. The pre context just includes properties which are able to be resolved prior to building a package, such as chainId, timestamp, and package.json contents.
may be helpful to update the documentation to explain exactly what is in the context during settings/version resolution, but the fact that other properties (such as the value of "other" settings) is not yet resolved.
tested using `sample-hardhat-project`
> add PreContext

- packages/builder/src/actions.test.ts
- packages/builder/src/actions.ts
- packages/builder/src/builder.test.ts
- packages/builder/src/builder.ts
- packages/builder/src/definition.ts
- packages/builder/src/steps/contract.ts
- packages/builder/src/steps/import.ts
- packages/builder/src/steps/invoke.ts
- packages/builder/src/steps/provision.ts
- packages/builder/src/types.ts
- packages/cli/src/custom-steps/run.ts
changes the default `targetPreset` from `main` (which causes problems and overwrites package versions and etc) to `with-${packageName}`, where `${packageName}` is the name of the currently being built package.
unfortunately, we currently have no way to know what package is currently being built, so the `currentLabel` which is ususally passed into actions has been augmented to support both the package name and version as well. The builder will automatically handle any organization of this.
> default `targetPreset` to a different context

- .github/workflows/lint.yml
- .github/workflows/test.yml
- packages/builder/src/abis/CannonRegistry.ts
- packages/builder/src/create2.test.ts
- packages/builder/src/create2.ts
- packages/builder/src/package.test.ts
- packages/builder/src/package.ts
- packages/builder/src/registry.test.ts
- packages/builder/src/registry.ts
- packages/builder/src/steps/import.ts
- packages/cli/src/commands/publish.ts
- packages/cli/src/index.ts
- packages/cli/src/util/provider.ts
recently more and more I have been finding that publish transactions tend to be very numerous, which is both expensive and arduous. It would be better if package publish calls were the minimum number possible.
Add a `publishMany` function to the CannonRegistry (which defaults to just calling `publish` in a loop. This function is overridden by OnChainRegistry, which will combine all the calls into a single multicall transaction
> use multicall on copy package publish

- packages/cli/src/commands/build.ts
- packages/cli/src/foundry.ts
- packages/cli/src/index.ts
- packages/website/content/docs-technical.md
Made cli build to support cannon file in another path
Removed misleading contracts-directory and artifacts-directory options from cli build command 
Removed unused variables
Ref #203
> CLI build non-local cannon file support

- packages/builder/src/actions.ts
- packages/builder/src/builder.ts
- packages/builder/src/steps/provision.ts
on rare occasion jsonrpc APIs will just send a transaction and then it never advances/gets picked up, but cannon still thinks it was successfully submitted.
when this occurs, it can cause cannon to be stuck indefinitely, and the user eventaully has to control-c to cancel the build. this is very bad, since control-c will lead to a loss of state and could impact future builds.
to prevent this, a global step timeout system is implemented. if a step exceeds its given time limit, its promise is immediately suspended and the step is marked as incomplete with `timeout without error`. the user can just retry after the build is complete if it really is just a dumb timeout issue with the api.
> prevent stalled steps by implementing a basic timeout system

- packages/builder/src/error/index.ts
- packages/cli/package-lock.json
- packages/cli/src/index.ts
- packages/cli/src/interact.ts
- packages/sample-hardhat-project/hardhat.config.ts
- packages/website/package-lock.json
fixes https://github.com/usecannon/cannon/issues/213
the general error here was a combo of:
* logs not being parsed correctly for cases where addresses are duplicated in contract list
* the `signers` that come back from frame do not pass through the error parser in cannon (and there probably isnt a way to fix this), but this is unnecessary so use raw `provider` instead
* frame error code was not in the error parser module
also a few more enhancements added:
* print out calldata and gas usage on read-only txns
* parse decimal amounts of ETH when specifying a payable amount
* ability to input `tuple` data types as arguments to a function
> fix parsing of some errors and logs in the interact command

- packages/cli/src/commands/build.ts
if a step is skipped, it is critical we print out hte actual reason why the step failed.
the change here is simple, if the error is just going to be `[object Object]`, stringify the object instead
result:
> prevent printing of `object Object` on skipped step

- packages/cli/src/commands/run.ts
- packages/cli/src/index.ts
unless the user specifies otherwise (either by including custom settings, or by including the `--build` flag), do not rebuild package on `cannon run`. instead rely entirely on existing snapshots of the top layers without checking if any steps need to be rebuilt.
This has a few benefits:
* much faster `run` command execution when not build
* avoid unexpected issues where package cannot be loaded for run due to local changes (ex. `synthetix-sandbox`). Package always runs as intended.
* eliminates need for plugins unless changing a package
* no significant change to command behavior otherwise
some behavior changes:
* list of contracts/transactions not printed out by default. I think this output is more useful overall, and if user wants a contract address they can find it in the interact cli
> dont build package by default on run command

- packages/builder/src/builder.ts
- packages/builder/src/runtime.ts
- packages/cli/src/commands/build.ts
if user pushes "control-c" or the process is sent a termination signal or similar, the process will attempt to finish the currently running step before quitting.
to verify fix, run a real build of `greeter` package on goerli. Press control-c while the library contract is being deployed. Observe how the greeter contract deploy step is skipped and a partial build is generated.
fixes #224
> add ability to finish build cleanly on interrupt

- .eslintrc.json
- packages/builder/src/builder.ts
- packages/builder/src/constants.ts
- packages/cli/src/rpc.ts
to prevent issues with people using older versions of anvil, or trying to load newer build versions of packages:
* bump build version to ensure older versions of cannon will be force updated before loading an incompatible package
* check version of anvil to ensure its new enough to use compressed state dumps, and reccomend foundryup if not.
(note: this does nothing for existing versions of cannon that didnt have the build version check. shhh.)
doesnt actually fix 201 but we put part of the issue in this pr so yea.
> bump build version, check anvil version

- nx.json
- package-lock.json
- packages/builder/src/index.ts
- packages/builder/src/package.ts
- packages/builder/src/runtime.ts
- packages/builder/src/steps/contract.ts
- packages/builder/src/util.ts
- packages/cli/src/commands/publish.ts
- packages/cli/src/commands/run.ts
- packages/website/package.json
new features (and a couple old) had some regressions.
also tighten up logging in some places, minor fixes like that
in particular:
* previously, if executing a build on a gitops repo or anything that uses
nested provisioning. the cancelling of the build will fail because the `cancelled`
boolean only gets applied to the top level runtime, but it needs to be shared between all runtimes
> regression and log fixes

- packages/builder/src/steps/import.ts
If deployment info isnt present, the import step outputs a log that says the deployment info was not found but it does not dynamically display the preset specified in the cannonfile (if there is one) and instead just defaults to referencing the 'main' preset
> Removed hardcoded default preset name from import step error message

- packages/cli/src/index.ts
When using a subdirectory to store your cannonfiles, if the build command was run from the project root directory then cannon would try to fetch artifacts using the subdirectory as the root-directory.
By using the process.cwd() [Node function](https://nodejs.org/api/process.html#processcwd) we can set the project directory to be relative to where the process is run. 
Here's a successful run after making the change and rebuilding:
> Subdirectory build fail

- packages/builder/src/builder.ts
This allows empty strings as a valid setting value.
> Allow empty strings as settings

- packages/cli/src/index.ts
related to #306
I have set **0** while building so it allocates the first free port to that
https://www.lifewire.com/port-0-in-tcp-and-udp-818145
As you see in the below pics I ran cannon in a tab and in another tab I wanted to build with cannon and I got error, but in this branch I did the same and it built successfully
* **before**
* **now**
> Run anvil on an available port instead of running in on 8545

- packages/builder/src/definition.test.ts
- packages/builder/src/definition.ts
the problem is that the layer resolution system did not just depend on having topological dependencies. As an additional requirement, steps should be arranged based on the *layer* that they appear on to prevent cases where a subdependency shared by two steps ends up being merged together on a lower layer, creating a internal dependency cycle.
thankfully, it is fairly easy to mitigate this issue. if, while scanning deep dependencies, we also return the `maxDepth` (which is the effective depth of the dependency that was just scanned) and recursively compute that, we can assign a layer depth to every action reasonably cheaply. After this, it is possible to sort all nodes by depth (nodes with higher depth are mathematically guarenteed to have all dependencies included over nodes with a lower …
> fix infinite loop issue with layer compute

- packages/cli/src/foundry.ts
- packages/cli/src/index.ts
Ref #286 
Before when running the build step using a path with cannonfiles in a subdirectory it would fail to find artifacts, on the contrary using a relative path would work. I implemented a fix by simply forcing the user to be in the project root directory when running the command so that it would always resolve the parent directory as the foundry project root (therefore being able to find the artifacts).  However this would break the use of relative paths when specifying a cannonfile like '../../packages/sample-foundry-project/cannonfile.toml', I implemented a fix that recursively checks for a 'foundry.toml' file to determine the foundry project root so getArtifacts always has context of the project root directory regardless of where the command is ran and/or where the cannonfiles are …
> Dynamic build path

- package-lock.json
- package.json
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/run.test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/index.ts
- packages/cli/src/registry.ts
- packages/hardhat-cannon/src/tasks/run.ts
seems there were some things about this new argument which got missed in the review:
* the helper text siad to run `--registry local` but the actual command was `--registry-priority local`
* argument didnt work for `run` command because the arguments were not passed through
* argument should have worked for `inspect` command also
> fix: bugs on `--registry-priority` argument

- packages/website/src/app/walletProvider.tsx
Closes #426
@noahlitvin I've fixed overflow issue, but there are too many options still. Looks like there is no way to add a search or something like that, so the only way is to specify chain list manually (right now we use all supported chains). Do you have some ideas about relevant chain list that we want to use? Or I can reduce it myself and we will add missing ones ad hoc.
> fix(website): fix chains modal overflow

- packages/website/src/features/Deploy/DisplayedTransaction.tsx
> feat(website): handle tuples in the queue transactions ui

- packages/cli/src/commands/trace.ts
- packages/cli/src/index.ts
- packages/cli/src/util/anvil.ts
* accept block tag (instead of just number) as the `--block-number` argument
* accept provider-url argument
* warn the user if the txn they inputted is probably not existing
* fix forking on correct block number not working properly
> fix: `cannon trace` bugs

- packages/website/content/docs-actions.mdx
Added these constants to documentation on website:
<%= Zero %>
<%= One %>
<%= Two %>
<%= WeiPerEther %>
<%= MaxUint256 %>
<%= MinInt256 %>
<%= MaxInt256 %>
> fix(docs): add cannonfile constants documentation

- packages/website/src/app/packages/[name]/[tag]/[variant]/layout.tsx
> fix(website): show publish time of the currently selected variant of the package

- packages/cli/bin/cannon.js
- packages/cli/src/helpers.ts
- packages/cli/src/settings.ts
often cannon cli would startup slow because the `npm view` command that is called to resolve the latest cannon version has to call the internet to get the latest version. Its not necessary to call out to the internet every time the user uses cannon to check for the latest version, just very periodically.
to solve this problem, the `npm view` command is called only once a week at max. in other cases, the version is loaded from a file stored in their cannon directory.
on my computer this brings the startup time of the cannon process from 1-2 seconds to start every time to near instant.
> fix(cli): much faster startup

- packages/cli/src/commands/run.test.ts
- packages/cli/src/commands/run.ts
this PR augments the `cannon run` command to support automatic tracing and decoding of executed transactions from inside the CLI upon execution. Currently, there are 2 trace output modes: console.log only, and full trace output.
A user can push the `v` to enable tracing and display of `console.log` trace events. If the user pushes the `v` command once more, they will be given the ability to see the full trace output. The logs are automatically decoded with the contents of the cannon package that is currently active.
demo: https://www.terminalizer.com/view/562c63b05783
fixes https://linear.app/usecannon/issue/CAN-10
> feat(cli): ability to trace transactions while in cannon run

- packages/builder/src/package.ts
- packages/cli/src/commands/verify.ts
when copying from local fs (aka file:// scheme), it is possible that an uploaded package can end up not having its url updated. this leads to builder issues because `file://` scheme artifacts generally only exist on the builder's system, so we have to make sure these get scrubbed out always.
to fix, the `forPackageRecursive` has been updated to automatically update the url stored inside the deployment info object if a url is returned by the copy function. for functions which do not return a url, this change has no effect.
> fix(builder): handling of package url modification during copy

- packages/cli/src/helpers.ts
- packages/cli/src/index.ts
When a user provides a providerurl and chainid, ensure that the chain ids match else display a proper error message
> fix(cli): proper error on providerurl chainid and chainid mismatch

- packages/builder/src/package.ts
it is possible that a package which has 2 levels deep of provision artifacts can preserve a rogue file link after being uploaded to ipfs
to prevent this, change the functionality of the url remapping in the forPackageTree function to support loading of chain artifacts.
this is kind of an expensive change, but we gotta do what we gotta do right?
i have tested this independently with the sample-hardhat-cannon project, and it worked as expected both for ipfs storage, and for file storage
> fix(builder): file links in recursive provision packages

- packages/cli/src/util/provider.ts
Removing fallbackprovider from provider resolution process. Was causing errors when trying to execute RPC `send` calls.
> fix(cli): remove fallback provider

- package-lock.json
- packages/builder/src/registry.ts
- packages/cli/src/registry.ts
as mostly a side effect of the change to use , combined with the lack of deployments until recently, there was a regression introduced for packages importing recently deployed packages in the same build which caused the just-deployed build to not be utilized by the imported package.
to resolve this issue, ensure that there is a `InMemoryRegistry` included with every fallback registry. this will ensure that the fallback registry, in and of itself, fulfills the registry mandate of returning the same output after putting an artifact into it.
fixes https://linear.app/usecannon/issue/CAN-104/usage-in-memory-during-build
> fix(builder): use in memory during build

- packages/cli/src/index.ts
thought this ws fixed before but basically, the port needs to be fixed while running `cannon test` command so that foundry anvil can connect during test run
> fix(cli): cannon test command failure

- packages/hardhat-cannon/src/tasks/build.ts
outside of cannon network it is totally fine to read from signers
> fix(hardhat-cannon): ensure execution signer is correct on cannon network

- packages/cli/src/util/provider.ts
Most people aren't using Frame, so I think this warning is confusing. In general, I think we should refactor this where it uses frame if available. If it detects frame, but it's not connected/on the wrong chain, it warns but plays through.
> chore(cli): Remove frame warning

- packages/cli/src/helpers.ts
uses semver library, which is alreayd a dependency, to determine if the new version is newer.
fixes https://linear.app/usecannon/issue/CAN-114
> fix(cli): only warn user of new version when new version is newer

- packages/cli/src/index.ts
- packages/cli/src/util/provider.ts
* separate the logic for signers depending on whether its frame or specified wallet
* if frame wallet is unsuccessful, automatically recurse to try the next provider. this works effectively for publishing
* at publish time, rather than checking if user supplied a private key, try to load signers, and if it does not succeed, prompt the user as we are now and then add signer that way
fixes https://linear.app/usecannon/issue/CAN-113
fixes https://linear.app/usecannon/issue/CAN-110:
> fix(cli): update provider resolving configuration

- packages/builder/src/package.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/publish.ts
- packages/cli/src/commandsConfig.ts
- packages/cli/src/index.ts
ability to upload just IPFS hash.
ex
fixes https://linear.app/usecannon/issue/CAN-112
> feat(cli): allow publish of ipfs hash through `deliver` command

- packages/cli/src/commandsConfig.ts
- packages/cli/src/index.ts
Added debugging flags to following cannon commands:
* run
* verify
* alter
* fetch
* pin
* publish
* inspect
* prune
* trace
* decode
* test
* interact
* setup
* clean
* plugin list
* plugin add
* plugin remove
> fix(cli): Implement global debug level settings using Commander lifecycle hooks

- packages/website/src/constants/deployChains.ts
- packages/website/src/features/Deploy/TransactionDetailsPage.tsx
- packages/website/src/features/Deploy/TransactionDisplay.tsx
- packages/website/src/hooks/backend.ts
- packages/website/src/hooks/safe.ts
webiset would not sign a transaction for nonce 0 on safe due to erronous comparison
also whilst fixing, found a few other issues with the website which I went ahead and fixed:
* sepolia network gnosis service url not set
* add warning to make it more clear if a service url is not set, prevent returning undefined which should not happen in useQuery
* fix website crashing on my test transaction (/deploy/txn/11155111/0x9A5A33e97A2C3942A3E933DD56E1373c12259345/0/0x2051adb5138a75f6f6938c08e8eaa535d920b88e7a197cf1dc9cf449a815f01c?chainId=11155111&address=0x9A5A33e97A2C3942A3E933DD56E1373c12259345) due to null checks
fixes https://linear.app/usecannon/issue/CAN-160/safe-nonce-0-does-not-work-on-the-website
> fix(website): issues with nonce 0 on safe

- packages/cli/src/index.ts
- packages/cli/src/loader.ts
- packages/cli/src/rpc.ts
does not use correct port for internal anvil instance. very disappointing. also added a change to make it easier to tell what file is being accessed by ipfs cli resolver
> fix(cli): cannon test command completely regressioned

- packages/website/src/components/CodePreview.tsx
- packages/website/src/features/GetStarted/SetupSection/FoundryGuide/CreateCannonFile.tsx
- packages/website/src/features/GetStarted/SetupSection/FoundryGuide/ImportProvisionPackages.tsx
- packages/website/src/features/GetStarted/SetupSection/FoundryGuide/TestYourProtocol.tsx
- packages/website/src/features/GetStarted/SetupSection/HardhatGuide/CreateCannonFile.tsx
- packages/website/src/features/GetStarted/SetupSection/HardhatGuide/ImportProvisionPackages.tsx
- packages/website/src/features/Packages/ChainDefinitionSteps.tsx
- packages/website/src/features/Packages/CodeExplorer.tsx
- packages/website/src/features/Packages/ViewAsCannonFileButton.tsx
- packages/website/src/features/Router/RouterPage.tsx
This is an example of what it looks like:
> feat(website): add toml to monaco editor

- packages/website/src/components/CodePreview.tsx
- packages/website/src/features/GetStarted/SetupSection/FoundryGuide/CreateCannonFile.tsx
- packages/website/src/features/GetStarted/SetupSection/FoundryGuide/TestYourProtocol.tsx
- packages/website/src/features/GetStarted/SetupSection/HardhatGuide/CreateCannonFile.tsx
- packages/website/src/features/Packages/CodeExplorer.tsx
This is an example of what it looks like:
> feat(website): Add solidity lang to monaco editor

- packages/hardhat-cannon/package.json
adds correct dist path to package.json so that the folder is included on publish.
> fix(hardhat-cannon): fix excluded dist folder from package

- packages/cli/src/chains.ts
- packages/cli/src/commands/alter.test.ts
- packages/cli/src/commands/build.test.ts
- packages/cli/src/index.ts
- packages/cli/src/util/build.ts
- packages/cli/src/util/provider.ts
- packages/hardhat-cannon/src/tasks/build.ts
test command:
```
xcannon build --chain-id 123420111 --provider-url https://rpc.op-celestia-testnet.gelato.digital/ --dry-run
```
> fix(cli): incorrect chain id resolution when specifying custom chain id

- packages/hardhat-cannon/src/subtasks/run-anvil-node.ts
- packages/hardhat-cannon/src/tasks/build.ts
* provider was not being passed into anvil node for forking
* chain id was not getting passed into build step to disable unnecessary persistence (leads to repetition/snapshot bugs which should not exist on fork)
> fix(hardhat-cannon): hardhat bugs in handling of params

- packages/builder/src/steps/contract.ts
- packages/builder/src/steps/invoke.ts
- packages/builder/src/steps/router.ts
- packages/cli/src/commands/build.ts
its hard to get viem to recognize the signer that it needs to use is the one thats already sitting in its wallet setup (?)
> fix: "unknown signer" errors occuring during certain build configurations

- packages/builder/src/constants.ts
- packages/builder/src/create2.test.ts
- packages/builder/src/create2.ts
- packages/builder/src/schemas.ts
- packages/builder/src/steps/contract.test.ts
- packages/builder/src/steps/contract.ts
- packages/hardhat-cannon/src/tasks/build.ts
for some reason gnosis safe uses their own address that they deployed of arachnid create2 for deploying their contracts.
> feat(builder): support for deployment through alternative address

- packages/builder/src/registry.ts
- packages/cli/src/commands/inspect.ts
- packages/cli/src/commands/prune.ts
- packages/cli/src/loader.ts
this command was first introduced a few months ago, but it hasnt really been used for anything official until now.
implement:
* support for specifying no `packageSpec` to filter by, aollowing for the entire registry to be scanned
* support for `getAllUrls` on registry with viem (it actually was supported)
> fix: cannon prune facelift

- packages/cli/src/index.ts
Closes https://linear.app/usecannon/issue/CAN-221/run-step-should-infer-chain-id-from-the-provider-url
> fix(cli): run command infer chain id from provider

- packages/builder/src/definition.ts
adds safety checks in case dependency steps are not found as expected.
this adds additional typesafety and also fixes issues in the case that 2.11.x cannon encounters newer package types
> fix(builder): chain definition handling improvements

- examples/sample-foundry-project/cannonfile.toml
- examples/sample-hardhat-project/package-lock.json
- packages/builder/src/builder.test.ts
- packages/builder/src/builder.ts
- packages/builder/src/definition.ts
- packages/builder/src/runtime.test.ts
- packages/builder/src/runtime.ts
- packages/builder/src/schemas.ts
- packages/builder/src/types.ts
- packages/cli/src/commands/inspect.ts
- packages/cli/src/helpers.ts
- packages/cli/src/util/build.ts
- packages/cli/test/e2e/scripts/non-interactive/build-foundry.sh
- packages/cli/test/e2e/scripts/non-interactive/build-hardhat.sh
- packages/hardhat-cannon/src/index.ts
- packages/hardhat-cannon/src/type-extensions.ts
previously, we used envvars/cannon config to decide whether or not to include contract source codes in the cannon data.
instead, now the storage of cannon source codes is determined by a global property in the cannonfile. this should solve all cases of determining whether or not to deploy contract sources safely, in roughly the same way that the npm package.json `private` key works
> feat: better handling of contract source codes omission

- packages/cli/src/index.ts
Changes the prompt for registry provider selection on publish to a single select. Fixes a bug with the pickedRegistryProviders coming back as undefined which causes a breaking error on publish.
> fix(cli): fixing registry provider prompt bug

- packages/website/src/hooks/backend.ts
This PR introduces a small fix aimed at enhancing the user experience within our web application by ensuring that pending signature transactions are automatically refreshed every 10 seconds. 
The attached vide demonstrates the fix. It showcases two browser windows side-by-side: the window on the right is used to perform a signature, and the window on the left automatically refreshes to reflect the completed signature without any user intervention. 
https://github.com/usecannon/cannon/assets/3952453/3b8c2a33-3836-4fe7-bb40-7ecb4fa9b091
> fix(website): refetch signatures data every 10 sec

- packages/website/src/hooks/safe.ts
The main goal of this PR is to ensure that safes are properly loaded for the connected wallet. Currently, we are encountering issues with some safe API requests failing, particularly on the Goerli and base-Goerli chains. This failure leads to the safe selector not offering any options. To address this, we are catching the errors in order to avoid breaking the whole query. This approach ensures that, despite failures on specific chains, the functionality for other chains remains working as expected.
This video demonstrates how the errors caught are associated with the Goerli and base-Goerli chains. However, it also shows that the safe selector is functioning correctly for other networks.
https://github.com/usecannon/cannon/assets/3952453/1f0d6ef5-065d-4ba0-9b71-0e921c6f4bb0
> fix(website): prevent breaking safes query - Safe selector Fix

- packages/website/src/providers/walletProvider.tsx
According to the migration guide found at [RainbowKit's documentation](https://www.rainbowkit.com/docs/migration-guide), we previously lacked the correct configuration for Rainbow version 2.x.x. This oversight led to the wallet being repeatedly disconnected and reconnected, forcing users to reconnect their wallets multiple times. With the recent fix, this issue has been resolved. As demonstrated in the video, users can now navigate and reload the page without losing their wallet connection.
https://github.com/usecannon/cannon/assets/3952453/f8c60a86-8cf7-4eca-b8a4-302f0b6f0462
> fix(website): rainbow 2.x.x migration - Wallet getting disconnected

- .github/workflows/test-e2e.yml
- .github/workflows/test-snx-ci.yml
- packages/builder/src/index.ts
- packages/builder/src/multicall.ts
- packages/builder/src/package.ts
- packages/builder/src/registry.test.ts
- packages/builder/src/registry.ts
- packages/cli/src/commands/publish.ts
- packages/cli/src/commands/register.ts
- packages/cli/src/commandsConfig.ts
- packages/cli/src/index.ts
- packages/cli/src/settings.ts
- packages/registry/test/contracts/CannonRegistry.test.ts
This PR adds the new `cannon register <packageName>` command to register for the first time on the main registry a new package. This is the first for unlocking new package publications.
**Next steps (on a separate PR):**
1. Merge functionality on `publish` command. This gets tricky as the publish command will have to check if the package is not registered, register it. If not, try to infer on which registry it should be published.
2. Add possibility to migrate packages from main registry to secondary one
**Extra**
* This PR also includes some heavy refactors on builders `registry.ts` file, but functionality is exactly the same.
> feat(registry): add `register` command for creating packages

- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
The main purpose of this PR is to make sure to use the current safe chainId to look up for previous published package instead of using the current wallet provider chainId
https://github.com/usecannon/cannon/assets/3952453/a77d2370-f7bf-4c0f-9ded-3307ce25105b
> fix(website): current safe chainId - queue cannon

- packages/cli/src/registry.ts
Currently, on the cli when executing the build command, it was being initialized with a FallbackLoader that included a OnChainRegistry, the problem with that is that when using a `clone` step that deploys a new package it's publishing to the registry [here](https://github.com/usecannon/cannon/blob/d0743d225b4d7fcc2ad1c9456d81107b1dc2e911/packages/builder/src/steps/clone.ts/#L215-L220), instead of failing and Fallbacking to the LocalRegistry.
This PR adds a ReadOnlyOnChainRegistry that fails in case we unknowingly do that.
> fix(registry): enforcement of read only registry usage on build

- package-lock.json
- packages/cli/package.json
- packages/cli/src/commands/build.test.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/index.ts
- packages/cli/src/loader.test.ts
- packages/cli/src/loader.ts
- packages/hardhat-cannon/package.json
This PR makes sure that the `Loader` used in the `publish` command does not write to remote ipfs node. On a future PR we can update all the other commands to not write to IPFS by default, except for publish, which is the only one that should do it.
Sorry for not adding a proper test case here, there are not tests on build command yet and it would take some time.
> fix(build): update build command to not write to remote ipfs

- packages/cli/src/index.ts
The CLI settings were expecting the flag to be called `--etherscan-api-key`, but it is defined as `--api-key` in the verify command config. Therefore, the Etherscan API keys sent by the flag were never used. To maintain backward compatibility, I think we can't rename the flag, but we can make it work with the current settings logic.
> fix(cli): verify command should use --api-key flag

- packages/cli/src/settings.ts
Fixes `Missing IPFS loader` bug appearing when ipfs urls aren't explicitly set in settings
> fix(builder): default to repo url if ipfs urls are empty while parsing settings

- packages/cli/src/commands/build.ts
This PR includes this fix when generating the `fullPackageRef` variable, which makes it use the given `--preset` arg. Which was missing.
And this is crucial, because afterwards we use it to calculate the previous tag on updates here: https://github.com/usecannon/cannon/pull/887/files#diff-3b0340e6f408eb23ee2bdd40008c9ca70e2f115de9f8369097574ab4c0b67c2fR96
> fix(build): usage of --preset argument

- packages/builder/src/steps/clone.ts
its not possible to restore a `clone` state cleanly if it chooses not to rebuild, so we force full rebuild every time.
> fix(builder): rebuild `clone` ops on snapshots

- packages/website/src/constants/deployChains.ts
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
any git ref should be usable in the cannonfile queue page
additionally, removed unsupported chains from gnosis safe server querying thing
btw, I couldn't get the git-proxy to work on my end for some reason. I wonder if this is just a local thing?
> fix(website): ability load cannonfile from hash or tag

- packages/builder/src/schemas.ts
nested arrays in objects were not working. it seems the only way to set up types is to use zod lazy.
I punted on the type because it offers very little benefit to check it.
> fix(builder): schema should allow for all possible arg types/structures

- .changeset/cuddly-impalas-drum.md
- .changeset/slow-bottles-brake.md
- examples/sample-hardhat-project/package-lock.json
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/registry.ts
- packages/cli/src/settings.ts
- packages/cli/test/e2e/config/settings.json
- packages/hardhat-cannon/src/internal/cannon.ts
When doing local development, it is sometimes preferred to not use IPFS or the on-chain registry and only rely on the local registry. 
When checking out a repository, the `builder` will always first obtain the [`oldDeployData`](https://github.com/usecannon/cannon/blob/b60540a70ce5e44926ae775ee4eb7fdfbb384ded/packages/cli/src/commands/build.ts#L170) from IPFS when building for the first time (populate the local registry/cache). However, if the IPFS endpoint is unreachable it will throw an uncaught exception and fail the build. 
```
Error: could not download cannon package data from "QmeHoNyUA38JUKPPcFPxiAYsDBUnCiHagzvFrYbryrP4XN": Error: connect ECONNREFUSED 0.0.0.0:5001
```
This is likely the preferred behavior, as if a deployment is notarized on the on-chain registry we expect it to be …
> feat(build): offline mode

- package-lock.json
- packages/builder/src/index.ts
- packages/registry/package.json
- packages/website/src/app/layout.tsx
This PR removes the custom `isIpfsGateway` helper on the website, and just uses the one from `@usecannon/builder`.
> fix(website): usage of isIpfsGateway helper on website

- package-lock.json
- packages/builder/src/abis/CannonRegistry.ts
- packages/registry/contracts/CannonRegistry.sol
- packages/registry/contracts/EfficientStorage.sol
- packages/registry/package.json
- packages/registry/test/contracts/CannonRegistry.test.ts
to prevent smart contract wallet which cant necessarily be claimed on all chains from being abused, we allow for setting of separate list of `additionalPublisher`s on optimism and mainnet.
this also furthermore means that publishing by the package `owner` address on optimism is not possible. If the user wants to be able to deploy with the same address on optimism, they need to add their owner to the optimism `additionalPublisher`'s list.
also took the opporitunity to clean up and update the names of all the fields to the `additionalPublishers` instead of deployer.
This is not a perfectly efficient setup, but its functional and the user doesn't have to see it directly.
> fix(registry): optimism registry has different list of signers from mainnet

- packages/website/src/app/deploy/layout.tsx
- packages/website/src/features/Deploy/QueueDrawer.tsx
- packages/website/src/features/Packages/Abi.tsx
- packages/website/src/features/Packages/Function.tsx
- packages/website/src/features/Packages/FunctionInput.tsx
- packages/website/src/features/Packages/FunctionInput/AddressInput.tsx
- packages/website/src/features/Packages/Interact.tsx
This PR aims to enhance the behavior of the queue drawer. With the proposed changes, the drawer will be displayed on every queuing action, regardless of whether the transaction is successfully added or encounters an error.
https://github.com/usecannon/cannon/assets/3952453/36d57fbd-3aa8-4485-a16a-5e675c19b34f
This PR also fixes the issue with the `Address[]` type, and other array params
https://github.com/usecannon/cannon/assets/3952453/419e1f50-ee6c-4dcb-9228-8aff8b4f1723
> fix(website): show queue drawer on queueing action

- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/hooks/cannon.ts
the types were not being followed
fixes https://linear.app/usecannon/issue/CAN-280/add-required-generator-and-timestamp-fields-to-web-app-deployments
> fix(website): include generator and timestamp in package info

- packages/cli/src/commandsConfig.ts
- packages/cli/src/index.ts
we do this by deprecating includeProvisioned and adding a new option (excludeProvisioned)
includeProvisioned now has no effect
> fix(cli): includeProvisioned by default

- packages/cli/src/index.ts
- packages/cli/test/e2e/scripts/non-interactive/test.sh
otherwise it throws off CI and tests etc.
> fix(cli): cannon should exit with same code as forge

- packages/website/src/hooks/backend.ts
For fresh wallets (nonce equals to 0) there was no possible to queue txs
https://github.com/usecannon/cannon/assets/3952453/1e698026-abef-4f12-b37d-df8b6d6d943f
> fix(website): allow fresh safes to queue txs

- packages/builder/src/package.ts
- packages/cli/src/commands/publish.ts
This PR fixes an incorrect output on the publish command where it wouldnt correctly filter out the parent package from the provisioned packages list.
Before:
After:
> fix(cli): fixing publish incorrect cloned package output

- packages/website/src/features/Deploy/NoncePicker.tsx
- packages/website/src/features/Deploy/QueueDrawer.tsx
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/features/Deploy/QueueTransaction.tsx
- packages/website/src/features/Deploy/SignTransactionsPage.tsx
- packages/website/src/hooks/backend.ts
A bug appeared where it was automatically setting the tx nonce to the current one, instead of the next one. This was fixed doing a refactor at [`src/hooks/backend.ts`](https://github.com/usecannon/cannon/blob/6ddf99ae185c2cb3a98d32f8918e195b0c458df3/packages/website/src/hooks/backend.ts#L19-L77) to make it calculate the nonce after the data was fetch.
This is how it is looking right now, by default sets the nonce as `lastNonce + 1`, and if you check the nonce override, will set the selector with `lastNonce`:
Also, a minor bug was fixed when rendering errors with `undefined` arguments:
Before:
After:
> fix(website): nonce selector

- packages/website/src/features/Packages/DeploymentExplorer.tsx
- packages/website/src/features/Packages/FunctionOutput.tsx
Previously, function call outputs were duplicated, rendering the same values in each output field.
- With the fix, the function call outputs are now being rendered as expected.
https://github.com/usecannon/cannon/assets/3952453/7d749a2e-45ac-46ad-8658-9bac96208231
- Functions which return tuples, or arrays of tuples (such as https://usecannon.com/packages/synthetix/latest/10-main/interact/synthetix/CoreProxy/0xffffffaEff0B96Ea8e4f94b2253f31abdD875847#selector-0x75bf2444 ) working as expected
https://github.com/usecannon/cannon/assets/3952453/ac48cc4a-4aea-42a1-b1c3-d450582b7321
> fix(website): function array outputs render

- packages/website/src/features/Deploy/NoncePicker.tsx
https://github.com/usecannon/cannon/assets/3952453/bcf4f686-30cb-4e76-bf10-65867e970e2c
https://github.com/usecannon/cannon/assets/3952453/0656ffbd-bdea-43dd-8bc2-07dfa33bcdf8
This PR in order to fix the following error, the error is caused due to a `useEffect` that's setting the pickedNonce even if no override option is set to true
https://github.com/usecannon/cannon/assets/3952453/4f759ed5-74a6-414c-9f56-a2122226ceec
With the fix:
https://github.com/usecannon/cannon/assets/3952453/a0629b5f-f792-41ba-9d3b-8907c49e33ee
> fix(website): do not set nonce if no override

- package-lock.json
- packages/website/src/features/Deploy/QueueDrawer.tsx
- packages/website/src/features/Deploy/QueueTransaction.tsx
- packages/website/src/hooks/cannon.ts
This PR proposed a new title for each enqueued TX, to show the package name.
This is specially useful when coming back from a previously saved state, if I don't remember from which package was created the TX, now it can be checked. 
(also updates the X icon for a 🗑️ )
Before:
After:
> fix(website): add packageName when enqueuing transactions

- packages/website/src/features/Deploy/QueueDrawer.tsx
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/features/Deploy/TransactionDetailsPage.tsx
- packages/website/src/hooks/backend.ts
The main purpose of this PR is to offer the user to switch to the right chain before executing/staging any transaction
https://github.com/usecannon/cannon/assets/3952453/eaf6339a-a36a-4ca7-b512-492498e2b1ba
> fix(website): offer to switch to right safe chain

- packages/builder/src/builder.ts
- packages/builder/src/package.test.ts
- packages/builder/src/package.ts
- packages/cli/src/commands/publish.test.ts
- packages/cli/src/commands/publish.ts
prevent unnecessary payment of fees, speed up ipfs uploads, and reduce ipfs waste by removing duplication
> fix(builder): extraneous publishes when they are not needed

- package-lock.json
- packages/api/package.json
- packages/api/src/config.ts
- packages/api/src/db/transformers.ts
- packages/api/src/helpers.ts
- packages/api/src/queries/contracts.ts
- packages/api/src/queries/functions.ts
- packages/api/src/queries/packages.ts
- packages/api/src/routes/search.ts
- packages/website/.env.local.example
- packages/website/src/helpers/api.ts
This PR makes sure that the API does not return a `500` in case it cannot parse a result from the database. It just ignores the result and `console.warn` it so it could be potentially parsed in the future.
As an extra, adds the possibility to set a custom API endpoint, mostly for dev/test purposes.
> fix(api): gentler parsing of redis results

- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
The main purpose of this PR is to:
- When previous package input is empty clear errors
- Show error when package input data does not fulfill the expected regex
- Just Fetch previous package data when regex is fulfilled
 
https://github.com/usecannon/cannon/assets/3952453/df311407-c003-4d6a-bc42-ba0fcaeff6d5
> fix(website): previous package input behavior

- packages/website/src/features/Packages/Function.tsx
This PR updates the transaction queuing behavior. Instead of opening the drawer for each queued transaction event, a toast notification will now display the total number of queued transactions.
https://github.com/usecannon/cannon/assets/3952453/c7ed409e-89d4-4236-a0ad-58563c3f6eb7
> fix(website): do not open drawer on queued txn

- packages/website/src/hooks/providers.ts
- packages/website/src/providers/walletProvider.tsx
This PR wants to fix the wallet disconnection issue.
It was caused because the `wagmiConfig` was started to being initialized inside the component, which cased the wallet connection to be resseted. With this fix is being moved to a react state var, and only initialized once or when needed.
> fix(website): wallet disconnect surprisely

- packages/builder/src/index.ts
- packages/builder/src/package.ts
- packages/cli/src/commands/publish.test.ts
- packages/cli/src/commands/publish.ts
This PR refactors the logic for calculating the publish packages, and now, when calling it from the CLI will first calculate everything that's going to do, show the confirmation, and then execute it.
Before, it was calculating the publishes 2 times, in different ways.
> fix(publish): over publish logs

- packages/builder/src/loader.ts
- packages/cli/src/loader.ts
This PR fixes the following output:
> fix(cli): output url store data

- packages/builder/src/definition.test.ts
- packages/builder/src/definition.ts
causes a number of bugs:
* tons of duplicate dependencies on upload (should save a good bit of space!)
* publish urls changing
* publish urls mismatching
* additional packages being published when they shouldn't because their publish urls posthumously change
> fix(builder): deps are modified by definition.ts

- packages/builder/src/package.test.ts
- packages/builder/src/package.ts
- packages/registry/test/contracts/CannonRegistry.test.ts
This PR fixes the correct handling of null terminators for the builder. Before that we where using ethers.js it adds an extra `00` at the end when calling `ethers.utils.formatBytes32String`, which meant that we couldn't register packages with 32 length, just 31. Since we moved to viem this is fixed because the `stringToHex` helper does not add the null terminator, and in turn this PR fixes the length validation to 32.
> fix(builder): package length check

- packages/cli/src/commands/publishers.ts
- packages/cli/src/commandsConfig.ts
- packages/cli/test/e2e/e2e-tests.bats
- packages/cli/test/e2e/scripts/non-interactive/publishers.sh
This PR wants to add e2e tests for the publishers command:
- Add a publisher on OP network
- Remove a publisher on OP network
- Add a publisher on Mainnet network
- Remove a publisher on Mainnet network
> feat(cli): add e2e tests for publishers command

- packages/api/src/errors.ts
- packages/api/src/index.ts
- packages/api/src/redis.ts
With the default redis reconnection strategy, the server would just wait until it can connect to redis with an exponential retry timeout, this lead to the server to just be waiting an "infinite" amount of time.
With this fix, now:
1. Redis retries reconnecting always every 5 secs (doesn't make sense to wait 150 secs on third retry)
2. After 5 retries, the server will halt with an error (this will restart the server and notify us by email, thanks to DO)
3. Now, the client instantly gets a `503` when redis is not available, so it can be correctly handled by the client, instead of having to wait something like 90 secs timeout.
> fix(api): redis reconnection strategy

- examples/sample-hardhat-project/package-lock.json
- package-lock.json
- packages/builder/src/actions.ts
- packages/builder/src/definition.test.ts
- packages/builder/src/definition.ts
- packages/builder/src/runtime.ts
- packages/builder/src/schemas.ts
- packages/builder/src/steps/clone.test.ts
- packages/builder/src/steps/clone.ts
- packages/builder/src/steps/deploy.test.ts
- packages/builder/src/steps/invoke.test.ts
- packages/builder/src/steps/pull.test.ts
- packages/builder/src/steps/router.test.ts
- packages/builder/src/steps/var.test.ts
- packages/registry/scripts/list-packages.ts
Closes https://linear.app/usecannon/issue/CAN-348/throw-an-error-if-you-have-stuff-in-your-operation-definition-thats
This PR does not allow to add invalid config values to step names, for example in `[deploy.Contract]` it would throw if you misspell `artifact =` as `artifacttt =`.
> feat(builder): add strict validation to steps attributes

- .eslintrc.json
- package-lock.json
- packages/indexer/package.json
- packages/indexer/src/config.ts
- packages/indexer/src/redis.ts
- packages/indexer/src/registry.ts
This PR aims to do some simple refactors, following some guidelines from the API:
1. On startup, instead of fetching the `registry` contract from the remote registry using cannon, just use the `address`and `abi` from `@usecannon/builder`.
2. Use `envalid` for handling env configs
3. Update redis connection, also adds the same reconnection logic as the API
> chore(indexer): simple refactors

- packages/cli/src/index.ts
Closes https://linear.app/usecannon/issue/CAN-342/when-executing-build-command-and-foundry-is-missing-it-throws-could
> fix(build): add foundry setup check before executing build

- packages/builder/src/access-recorder.ts
access recorder can incorrectly handle some CannonHelperContext helpers if they are nested in an object
to fix this, update the function to properly handle nested objects.
tested on actual issue occuring on synthetix v3 repository
> fix(builder): ability to handle nested helper context

- packages/website/src/features/Deploy/PublishUtility.tsx
- packages/website/src/hooks/backend.ts
Before: 
Now:
fixes https://linear.app/usecannon/issue/CAN-308/more-clear-error-on-insufficient-funds-when-publishing
> fix(website): Add error message for insufficient funds on deployer

- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/features/Deploy/TransactionDetailsPage.tsx
- packages/website/src/hooks/cannon.ts
Closes https://linear.app/usecannon/issue/CAN-409/throw-an-error-when-trying-to-deploy-a-contract-using-the-web-deployer
This PR now shows an error when trying to stage a Safe transaction with a contract deployment:
> fix(website): simulation of deploy contract

- packages/builder/src/runtime.test.ts
- packages/builder/src/runtime.ts
- packages/builder/src/schemas.ts
- packages/builder/src/steps/router.ts
- packages/builder/src/types.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commandsConfig.ts
- packages/cli/src/util/anvil.ts
- packages/cli/src/util/build.ts
the arguments were not parsable or usable at all because they would be passed through multiple processes
now the command works as expected, parsing the inputted value in gwei and converting it early on to avoid ambiguity
> fix(cli): parsing and application of `--gas-price` and related

- packages/website/src/hooks/cannon.ts
- packages/website/src/hooks/registry.ts
- packages/website/src/pages/_app.tsx
- packages/website/src/pages/_providers.tsx
- packages/website/src/providers/CannonRegistryProvider.tsx
The `useCannonRegistry` hook is utilized by `useCannonBuild` and `useCannonPackage`, which are hooks used in many components. Previously, each component that consumed one of these hooks would trigger the creation of provider instances for all chains. This refactor ensures that these instances are created only once when the dApp is initialized.
Ideally, we should identify all top-level components using the hook and register the provider at the highest appropriate level. However, given the widespread use of these hooks, defining it on the `_app.ts` file seems temporarily a valid option.
> chore(website): replace useCannonRegistry hook with CannonRegistryProvider

- packages/builder/src/steps/invoke.ts
When the `fromCall.func` function doesnt exist or is invalid, the error incorrectly prints out the value for the `func` defined function
> fix(builder): Fix output for invalid fromCall.func

- packages/website/src/features/Deploy/DisplayedTransaction.tsx
- packages/website/src/helpers/chains.ts
- packages/website/src/helpers/formatters/index.ts
- packages/website/src/hooks/cannon.ts
- packages/website/src/pages/_app.tsx
This fix addresses the issue in [#411](https://linear.app/usecannon/issue/CAN-411/website-displays-wrong-function-when-same-name-on-sign-transaction), where the code was incorrectly retrieving the first matching function inputs from the ABI. Now, it selects the function inputs by matching the function name and the exact count of arguments specified in the decodedFunctionData.
- All the `any`s have been removed from `DisplayedTransaction.tsx`.
- I've refactored the code a bit, especially renaming some variables to make it more understandable. 
Closes https://linear.app/usecannon/issue/CAN-411/website-displays-wrong-function-when-same-name-on-sign-transaction
> fix(website): Correctly matching function inputs in ABI when signing a transaction

- packages/website/src/features/Ipfs/Download.tsx
- packages/website/src/features/Packages/CannonfileExplorer.tsx
- packages/website/src/features/Packages/CodeExplorer.tsx
- packages/website/src/features/Packages/DeploymentExplorer.tsx
- packages/website/src/features/Packages/Interact.tsx
- packages/website/src/features/Packages/IpfsLinks.tsx
- packages/website/src/features/Packages/Tabs/InteractTab.tsx
- packages/website/src/helpers/misc.ts
- packages/website/src/hooks/ipfs.ts
- packages/website/src/pages/packages/[name]/[tag]/[variant]/_layout.tsx
This PR addresses the lack of typing in the `useQueryIpfsData` hook, which has been split into two distinct hooks: `useQueryIpfsDataParsed` for converting data into JSON objects and `useQueryIpfsDataRaw` for retrieving raw data as an ArrayBuffer. This change ensures components can reliably understand the data type returned and correctly handle errors.
The motivation for this change was that the frontend was unprepared to manage scenarios where data parsing failed when calling `useQueryIpfsData`.
Modifications have been made where the dApp previously utilized the original hook to now use either `useQueryIpfsDataRaw ` or `useQueryIpfsDataParsed`, depending on the expected data format.
Due to the widespread impact of these changes, a deep code review and extensive testing of the dApp are …
> refactor(website): useQueryIpfsData

- packages/website/src/features/Packages/Abi.tsx
- packages/website/src/features/Packages/Tabs/InteractTab.tsx
- packages/website/src/pages/packages/[name]/[tag]/[variant]/interact/_layout.tsx
This PR fixes two bugs:
1. When moving among contracts listed in the header in the interact section, methods lose reference and fail when trying to call them with a message similar to this one: "Args parameters don't match". It was fixed by setting a unique key on the map that renders the box with the functionality to interact with the method. Before, it was using the `map.index` as the key, now the key is created using the contract address and the method selector. 
2. I've also fixed the issue where the contract selected loses the "selected border" when moving between methods.
> fix(website): CAN-431 Navigating among contracts in interact losses method references.

- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/features/Deploy/TransactionDetailsPage.tsx
- packages/website/src/features/Deploy/TransactionDisplay.tsx
This PR fixes an issue on the deploy page where an error is thrown:
```
Error: Invalid package reference "@ipfs:QmcYmR6na4ifqdT832trDfa9oYnsS3GS8ky1r8zCxumM5P". Should be of the format <package-name>:<version> or <package-name>:<version>@<preset>
at PackageReference.parse (webpack-internal:///../builder/dist/src/package.js:40:19)
at new PackageReference (webpack-internal:///../builder/dist/src/package.js:81:41)
at FallbackRegistry.getUrl (webpack-internal:///../builder/dist/src/registry.js:134:36)
at queryFn (webpack-internal:///./src/hooks/cannon.ts:278:40)
at Object.fetchFn [as fn] (webpack-internal:///../../node_modules/@tanstack/query-core/build/modern/query.js:189:14)
at run (webpack-internal:///../../node_modules/@tanstack/query-core/build/modern/retryer.js:93:49)
at eval …
```
> fix(website): use package ref instead of ipfs hash

- package-lock.json
- packages/builder/src/constants.ts
- packages/website/package.json
- packages/website/src/features/Deploy/DisplayedTransaction.tsx
- packages/website/src/features/Deploy/PublishUtility.tsx
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/features/Deploy/TransactionDetailsPage.tsx
- packages/website/src/features/Deploy/TransactionDisplay.tsx
- packages/website/src/hooks/cannon.ts
- packages/website/src/hooks/registry.ts
This PR fixes a bug where the `PublishUtility` was trying to fetch the package ipfs url by ipfs url instead of package name. With this fix it just returns the given ipfs url and correctly resolves the `fullPackageRef` when necessary.
> fix(website): publish utility was not loading package correctly

- packages/cli/src/commands/alter.ts
- packages/cli/src/index.ts
Closes https://linear.app/usecannon/issue/CAN-440/cannon-alter-packagename-set-contract-address-chain-id-xx-subpkg
This PR was used to debug the `set-contract-address` cannon command when editing subpackages.
1. ~~It adds the `--no-publish` flag to be able to test out new ipfs builds without having to publish to the registry~~
2. Rewrites the `set-contract-address` to make it more readable and make sure that only finds 1 step by the given name
3. Adds params validations in case of missing commands and some extra `debug` statements.
> fix(alter): update contract address on subpackages

- packages/cli/src/commands/build.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/helpers.test.ts
- packages/cli/src/write-script/types.ts
Because code of `cli` references sources of `builder` instead of referencing compiled dist files tsc includes whole cannon source when compiling downstream projects and fails to build.
> fix: Invalid import references

- packages/builder/src/helpers.ts
Viem currently does not have implemented the `evm_setAccountCode` method. I have added this code as a workaround to make it work on the website where we're using Ganache.
> fix(builder): use `evm_setAccountCode` when loading precompiles

- packages/website/src/helpers/multisend.ts
- packages/website/src/hooks/backend.ts
Closes [CAN-374.](https://linear.app/usecannon/issue/CAN-374/address-assorted-web-app-concerns)
Fixes an issue on interact section. When a tx was staged with a value like 2222^18 it was failing becuase the value (most of the times passed as string) was converted to Number instead of a BigInt.
> fix(website): CAN-374 stage TX with value

- packages/website/src/helpers/chains.ts
- packages/website/src/pages/packages/[name]/[tag]/[variant]/cannonfile/index.tsx
- packages/website/src/pages/packages/[name]/[tag]/[variant]/code/index.tsx
- packages/website/src/pages/packages/[name]/[tag]/[variant]/index.tsx
- packages/website/src/pages/packages/[name]/[tag]/[variant]/interact/index.tsx
When an unknown chain id is used in a package, we get an application error when trying to access that packages page on the web app.
Added a placeholder chain config so that when unknown chains are used, it defaults to that.
> fix(website): Fix unknown chain bug in package page

- packages/builder/src/constants.ts
- packages/cli/src/commands/setup.ts
- packages/cli/src/index.ts
- packages/cli/src/settings.test.ts
- packages/cli/src/settings.ts
* fix settings to be able to load registry settings from file successfully
* add tests to verify that file settings, env settings, and their interplay work as expected
* updates the builder constants to use our own infura service (the infura is gated to only accept requests relating to our registry contracts and no others)
> fix: a number of issues with cannon settings handling

- packages/builder/src/schemas.ts
For example, this kind of string was failing before on every property using the `interpolatedRegex`:
```
[pull.example]
source = "<%= settings.pkg %>@main"
```
> fix(builder): Let interpolated strings include other strings 

- packages/website/src/features/Deploy/DisplayedTransaction.tsx
The error above was ocurring because the contract name lookup on the `contracts`  array inside `DisplayedTransaction.tsx` didnt have a null check.
> fix(website): Add null check to variable on txn display

- packages/builder/src/registry.ts
Any errors that happen while trying to communicate with the RPC during read operations on optimism were being skipped, which is why the fallback registry would try mainnet even though it may result in fetching the wrong package info.
Adding a throw statement resulted in the RPC error being thrown when a read operation fails due to an RPC issue. 
fixes https://linear.app/usecannon/issue/CAN-470/differentiate-errors-better-on-the-fallback-registry
Examples:
Package only on Ethereum mainnet throws rpc error if there is one:
https://www.loom.com/share/bfea17e267f4436395dcdac94e2afd9d
Package only on Ethereum mainnet throws rpc error if there is one:
https://www.loom.com/share/393264be32cd44bcbb499e800521d0aa
Package on both networks does not fall back to eth mainnet if theres an rpc error: …
> fix(builder): Error passthrough on rpc errors

- package.json
- packages/cli/src/commands/inspect.ts
closes https://linear.app/usecannon/issue/CAN-457/cannon-inspect-has-an-extraneous-log
This PR makes sure that the build is not generating any extraneous logs when running `cannon inspect --json`, as the only expected output should be the JSON result.
Nevertheless, debug logs can still be used with:
```
DEBUG=cannon:cli:inspect dcannon inspect ...
```
> fix(inspect): debug info

- packages/website/src/features/Packages/DeploymentExplorer.tsx
- packages/website/src/features/Packages/PackageAccordionHelper/index.tsx
https://www.loom.com/share/74000c82035b479baa3d79bbcc1b3fe5
Also added search bar:
https://www.loom.com/share/ae9a2cc03b2d4de1b44e549ed9c52e3a
The search bar above enables searching for any value under each column, so Operations, contract names and addresses, as well as specific transaction hashes.
Also fixes a bug where if a package has a run step in its definition it would break the site
Example: https://usecannon.com/packages/synthetix/2/1-main
fixes https://linear.app/usecannon/issue/CAN-472/show-any-contracts-that-are-deployed-on-contract-page-front
> fix(website): Display all contracts in a package in deployments tab

- packages/website/src/features/Search/PackageCard/DataTable.tsx
- packages/website/src/features/Search/SearchPage.tsx
Closes https://linear.app/usecannon/issue/CAN-525/y-scroll-on-explore-page-is-wonky
> fix(website): explore page scroll

- packages/cli/src/rpc.ts
- packages/cli/src/util/anvil.ts
some packages have gotten so big, they no longer fit in the standard request size for anvil. Thanksully, anvil now provides an escape hatch for this. Let's use it.
> add `--no-request-size-limit` to default anvil options

- packages/cli/src/rpc.ts
- packages/cli/src/util/anvil.ts
Hotfix coming from https://github.com/usecannon/cannon/pull/1379/
> chore(hotfix): add `--no-request-limit` to default anvil options

- packages/builder/src/builder.test.ts
- packages/builder/src/builder.ts
- packages/builder/src/types.test.ts
- packages/builder/src/types.ts
- packages/builder/src/util.test.ts
- packages/cli/src/helpers.ts
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/helpers/cannon.ts
Closes https://linear.app/usecannon/issue/CAN-538/on-cannonfiles-the-timestamp-variable-should-be-of-type-number
This PR fixes the necessity on having to cast the `timestamp` variable to `number` on cannonfiles on cases like this one:
> fix(builder): ctx timestamp type

- packages/website/src/hooks/ipfs.ts
This PR fixes an error on IPFS file fetch that made it not work when on `https://usecannon.com` because of the following restriction:
> fix(website): protocol fallback

- .github/workflows/upload-to-ipfs.yml
This PR remoces the "Upload Website to IPFS" github action from Pull Requests, but still let's the user execute it from the repo settings.
> chore(ci): remove upload to ipfs from pull requests

- examples/sample-foundry-project/src/Greeter.sol
- examples/sample-foundry-project/src/sub/AnotherDummy.sol
- packages/builder/src/steps/deploy.ts
- packages/cli/package.json
- packages/cli/src/foundry.test.ts
- packages/cli/src/foundry.ts
- packages/cli/src/helpers.ts
- pnpm-lock.yaml
PR with fixed branch name of https://github.com/usecannon/cannon/pull/1435
also significanlty improves the speed by removing calls to foundry commands. Warp speed.
also fix number of constructor arguments not being checked for contract deployment (tbh surprised viem doesn't do this automatically but whateves)
> fix(buidler): foundry build issues

- lerna.json
- packages/builder/package.json
- packages/cli/package.json
- packages/cli/src/commands/config/forge/common/evm.ts
- packages/hardhat-cannon/package.json
This PR fixes a bug where the `cannon test` command with `--rpc-url` was conflicting and throwing the following error:
```bash
> cannon test cannon.toml --rpc-url https://ethereum-sepolia-rpc.publicnode.com
error: the argument '--fork-url <URL>' cannot be used multiple times
```
> fix(cli): forge test param with fork-url

- package.json
- packages/api/package.json
- packages/builder/package.json
- packages/cli/package.json
- packages/hardhat-cannon/package.json
- packages/indexer/package.json
- packages/registry/package.json
- packages/repo/package.json
- packages/website/package.json
This PR makes sure that we are not adding unused files from previous builds on a new published package to npm.
It can happen when we run build on a package because it won't delete files from the `dist` folder that was deleted from `src`, so, it would be added to the npm package publish.
> fix(build): add clean command before build

- packages/builder/src/ipfs.ts
- packages/builder/src/steps/clone.ts
Backport to `v2.17` the fix added here: https://github.com/usecannon/cannon/pull/1420/files#diff-950232bdec873b2ee3a9f82132b20b978b8ae9fcf3be3a475e613efee95046f6R260
> chore(website): backport ipfs misc order

- packages/website/src/components/Alert.tsx
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
Only show the execute button on queue deploy if there are no safe steps.
Tested with: https://github.com/nicosampler/weth/blob/main/cannonfile.nodeployers.toml
> fix(website): CAN-582

- packages/cli/src/write-script/render-ethers.ts
- packages/cli/src/write-script/render-foundry.ts
- packages/cli/src/write-script/write.ts
Closes https://linear.app/usecannon/issue/CAN-586/add-foundry-script-output-format-to-the-write-script-param
Example output:
```bash
#!/bin/bash
export PRIVATE_KEY=<your_private_key>
export RPC_URL=<your_rpc_url>
echo "Executing: [deploy.Greeter]"
cast send --private-key $PRIVATE_KEY --rpc-url $RPC_URL --create 0x...
echo "Executing: [invoke.setGreeting]"
cast send --private-key $PRIVATE_KEY --rpc-url $RPC_URL 0x...
echo "Transactions complete."
```
> feat(cli): --write-script-format has foundry option

- package.json
- packages/builder/package.json
- packages/builder/src/steps/router.ts
- packages/builder/src/utils/compile.ts
- packages/builder/tsconfig.json
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- pnpm-lock.yaml
Closes https://linear.app/usecannon/issue/CAN-596/allow-to-build-the-router-on-website-using-solc
> feat(router): CAN-596 add web-solc to compile on browser

- packages/builder/src/schemas.ts
- packages/cli/src/commands/build.test.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/util/build.ts
- packages/hardhat-cannon/src/internal/cannon.ts
- packages/hardhat-cannon/src/tasks/build.ts
Bug: The output incorrectly shows that the package is closed source, even though this is not specified in the Cannonfile.
Cannonfile example:
```
name = "example-token"
version = "1.0.0"
description = "Example token"
preset = "main"
[setting.salt]
defaultValue = "salt"
[setting.name]
defaultValue = "Token"
[setting.symbol]
defaultValue = "TKN"
[setting.initialSupply]
defaultValue = "0"
[setting.owner]
defaultValue = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
[contract.MintableToken]
artifact = "MintableToken"
from = "<%= settings.owner %>"
salt = "<%= settings.salt %>"
args = [
"<%= settings.name %>",
"<%= settings.symbol %>",
"<%= settings.initialSupply %>",
]
create2 = true
highlight = true
```
Build output:
```
Initializing new package...
Name: example-token
Version: 1.0.0
Preset: …
```
> fix(cli): Incorrect display of `privateSourceCode` in CLI output

- packages/builder/src/schemas.ts
- packages/website/src/features/Docs/DocsCannonfilesPage.tsx
- packages/website/src/hooks/cannonfileSpecs.ts
This PR includes changes on the https://website-lrrh8g5w8-cannon.vercel.app/learn/cannonfile section.
1. Fixes the `deployers` key documentation
2. Updates the `Constants` section with real data
3. Adds a section for `Utilities`
4. When referencing step types, instead of writing `pull` write it as `[pull.*]` to make it more clear that is a step name and differentiate it from other sections
> hotfix(docs): fix cannonfile spec docs

- packages/website/src/features/Packages/Function.tsx
- packages/website/src/features/Packages/FunctionOutput.tsx
Fix method call on interact for Tuple types.
A rename was done, because the current names were too confusing.
> fix(website): CAN-609

- packages/builder/src/helpers.ts
This PR aims to remove a workaround that was implemented when Viem did not yet include the setCode function for Ganache. Related PR: https://github.com/wevm/viem/pull/2636
> chore(builder): switch to Viem's setCode for Ganache

- packages/cli/src/commands/config/index.ts
- packages/cli/src/util/build.ts
This PR aims to simplify the code around configuring signers, improving readability while maintaining the same behavior.
> chore(cli): refactor `configureSigners` function

- packages/cli/src/commands/build.ts
- packages/cli/src/commands/config/index.ts
- packages/cli/src/index.ts
Add `--skip-upgrade-record` to `cannon build` command in case of an emergency the user does not want to create a record on chain about the build.
> feat(cli): add --skip-upgrade-record flag

- packages/cli/src/index.ts
Running `cannon build` with `--dry-run` without specifying the `--chain-id` should throw an error.
Bug:
```
cannon build mintable-token.cannonfile.toml --dry-run
Building the foundry project...
forge build succeeded
Anvil instance running on: http://127.0.0.1:61073
shutting down existing anvil subprocess 24191
/usr/local/lib/node_modules/@usecannon/cli/dist/src/rpc.js:69
throw new Error('Cannot set both an anvil forkUrl and a proxy provider connection');
^
Error: Cannot set both an anvil forkUrl and a proxy provider connection
at runRpc (/usr/local/lib/node_modules/@usecannon/cli/dist/src/rpc.js:69:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ChildProcess.<anonymous> (/usr/local/lib/node_modules/@usecannon/cli/dist/src/rpc.js:81:25)
Node.js …
```
> fix(cli): cannot build on Cannon network with --dry-run

- packages/website/guides/test-with-cannon.mdx
- packages/website/src/features/Docs/DocsLandingPage.tsx
- packages/website/src/features/HomePage/HomePage.tsx
- packages/website/src/pages/learn/guides/index.tsx
- change links from `/introduction` to `/setup`
- add solidity test file example
> fix(links-guides): fix links to /setup and add test solidity file

- packages/website/postcss.config.js
- packages/website/src/components/ui/tooltip.tsx
- packages/website/src/features/Search/PackageCard/DataTable.tsx
- packages/website/tailwind.config.js
Added the tooltips next to "Preset" in the table header
Also fixed z tag to prevent tooltip content under a modal
> fix(website): version dialog preset

- .github/workflows/backmerge.yml
This PR adds a GitHub Action workflow that automatically merges changes from `main` back to `dev` branch.
- Automatically triggers when changes are pushed to `main`
- Attempts to merge `main` into `dev` automatically
- If merge succeeds, pushes directly to `dev`
- If conflicts occur:
- Creates a new branch `backmerge/main-to-dev-{timestamp}`
- Opens a PR from this branch to `dev`
- Allows manual conflict resolution through PR interface
- Keeps `dev` branch up-to-date with `main`
- Reduces manual work for developers
- Provides clear process for handling merge conflicts
- Maintains clean git history
> feat(ci): add a github action to backmerge everything added on main to dev

- packages/website/src/providers/CannonProvidersProvider.tsx
This PR adds the possibility for changing the default rpcs given by viem. In our case this is necessary because we've been seeing that the default Sepolia rpc does not work properly for the users on the website.
> fix(website): add custom default rpcs

- packages/builder/src/ipfs.ts
- packages/repo/package.json
- packages/repo/src/s3.ts
- pnpm-lock.yaml
Noticed that the default configuration for the `axios-retry` library we were using for making retries when a IPFS POST request fail was not triggered on `POST` requests, this PR fixes that.
And, as an extra retry measure, retries were added when making S3 requests on repo.
> fix(cli): retries to IPFS were not being done

- packages/website/src/components/IpfsSpinner.tsx
- packages/website/src/features/Search/PackageCard/PackageCardExpandable.tsx
- packages/website/src/features/Search/PackageCard/PackageTable.tsx
- fixed [CAN-642](https://linear.app/usecannon/issue/CAN-642/vertically-center-ipfsloaders-under-all-of-the-tabs)
- Replaced the sentence with icons PinBottomIcon and PinTopIcon for mobile
- Showed only mainnet deployments
> fix(website): layout change for mobile

- packages/website/src/features/Packages/CodeExplorer.tsx
- packages/website/src/features/Packages/code/FileTreeItem.tsx
FIxed [CAN-671](https://linear.app/usecannon/issue/CAN-671/default-the-code-sidebar-to-be-open-to-the-main-sol-file-for-the)
> fix(website): fix a default filetree

- packages/website/src/features/Packages/FunctionInput/AddressInput.tsx
- packages/website/src/features/Packages/FunctionInput/ByteInput.tsx
Fixed [CAN-667](https://linear.app/usecannon/issue/CAN-667/remove-white-border-keep-just-red-on-destructive-state-for)
> fix(website): remove white border on the destructive state

- packages/website/src/features/Packages/CannonfileExplorer.tsx
Fixed the height on Raw Cannonfile tab properly
Also adjusted the codes's width to avoid overlapping with scroll bars.
> fix(website): rawcannofile height issue

- packages/website/src/components/AbiParameterPreview.tsx
- packages/website/src/components/layouts/SidebarLayout.tsx
- packages/website/src/components/snippet.tsx
- packages/website/src/features/Deploy/DisplayedTransaction.tsx
- packages/website/src/features/Docs/DocsCannonfilesPage.tsx
- packages/website/src/features/Header/Header.tsx
- packages/website/src/features/Packages/Abi.tsx
- packages/website/src/features/Packages/Function.tsx
- packages/website/src/features/Packages/FunctionOutput.tsx
- packages/website/src/pages/_app.tsx
This PR refactors the Abi Input renderer from the TransactionDisplay component into a separate component, which then it is reutilised for rendering interact outputs. Effectively fixing some rendering bugs for rendering arrays and objects which were already solved on the TX view.
It also fixes the rendering of non-values for objects and arrays, generating an template result with zeroed values (working the same way as Solidity).
> fix(website): interact render of objects

- packages/website/src/features/Deploy/NoncePicker.tsx
- packages/website/src/features/Deploy/PreviewTransactionsButton.tsx
This PR fixes the nonce override picker when there are multiple TXs with the same nonce:
Also, does not allow to press the preview button when it is loading data.
> fix(website): nonce override picker

- packages/website/src/features/Deploy/CannonFileInput.tsx
- packages/website/src/features/Deploy/PrevDeploymentStatus.tsx
- packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
- packages/website/src/features/Deploy/hooks/useCannonPackage.ts
This PR fixes a bug that caused to not show the "Previous Package" input when deploying without using the `deployers =` params:
> hotfix(website): show upgrade from input

- packages/cli/src/foundry.ts
Fix compatibility when foundry saves artifacts with `contactName` including fully qualified name, e.g. `contractName: "src/Example.sol:Example"` instead of only the actual contract name.
> fix(cli): foundry contractName compatibility

- packages/builder/jest.config.ts
- packages/builder/src/package-reference.ts
- packages/builder/src/schemas.ts
- packages/builder/src/steps/clone.test.ts
- packages/builder/src/steps/pull.test.ts
Preset length was not being validated, this causes that when generating the variant for publishing to the registry it can end up being more than 32bytes. Luckily, this fix is not going to break any already published package as the current preset max length published is `24bytes`.
This is the original error that was being thrown when trying to pin/publish:
```
cannon pin ipfs://Qm...
Uploading package data for pinning...
Error: SizeOverflowError: Size cannot exceed 32 bytes. Given size: 36 bytes.
Version: viem@2.23.2
at FallbackRegistry.getUrl (/Users/**/.nvm/versions/node/v20.10.0/lib/node_modules/@usecannon/cli/node_modules/@usecannon/builder/dist/src/registry.js:147:23)
at async pinIpfs 
```
And now, with the fix it doesn't even allow you to build the package:
> hotfix(builder): add preset length validation

- packages/cli/src/commands/config/index.ts
- packages/cli/src/index.ts
its an extremely common error that unexpected signers are needed to complete a deployment, so this will ensure that a user has to be explicit about which signers should be required.
this is a breaking change, of course. Roll it in with all the others coming out in the next release.
TODO: do we need to check if `--private-key` is provided also? if it is then it could be treated as an implicit `--impersonate`
> require `--impersonate` or `--impersonate-all` on dry run builds

- packages/cli/src/foundry.ts
sometimes 2 files can be resolved for a contract when there should only be one
> hotfix(cli): foundry file resolution

- .github/workflows/website-e2e.yml
- examples/sample-foundry-project/cannonfile.toml
- packages/website/cypress/integration/Deploy.feature
- packages/website/cypress/utils/wagmi-mock-config.ts
- packages/website/src/providers/CannonProvidersProvider.tsx
configured providers for cypress were not being used on the `Interact` page, so it was flaking.
> use test cypress providers everywhere

- packages/cli/test/e2e/series.bats
many have tried to fix this failing CI test over the last few days with no success. At some point we have to admit defeat and not let this derail the entire operation.
> remove indefinite CI test that nobody can figure out

- packages/website/src/components/AbiParameterPreview/index.tsx
- packages/website/src/features/Search/PackageCard/DataTable.tsx
Fixed [CAN-737](https://linear.app/usecannon/issue/CAN-737/add-some-marginpadding-to-the-right-of-the-copy-button-here-to-match) and [CAN-489](https://linear.app/usecannon/issue/CAN-489/add-a-copy-button-to-the-ipfs-hash-in-the-packages-table)
- Adjust its position in interact page.
- Add the clipboard button on the package page.
[CAN-737](https://linear.app/usecannon/issue/CAN-737/add-some-marginpadding-to-the-right-of-the-copy-button-here-to-match)
[CAN-489](https://linear.app/usecannon/issue/CAN-489/add-a-copy-button-to-the-ipfs-hash-in-the-packages-table)
> fix(website): fix clipboard button position

- packages/cli/src/commands/interact.ts
the `highlighted` property is no longer guarenteed to be seen on a contract artifact, so adding a question mark ensures that case is properly handled
> fix crash on is highlighted

- packages/website/src/features/Deploy/SafeAddressInput.tsx
use `replace` instaed.
not using this makes it difficult/impossible to use the back button to go back.
https://linear.app/usecannon/issue/CAN-679/infinex-requests
> prevent browser from pushing path to history when

- packages/builder/src/steps/invoke.test.ts
- packages/builder/src/steps/invoke.ts
its a bit wierd how viem handles it, converting to an array if *any* of the fields are unnamed.
fixes https://github.com/usecannon/cannon/issues/1778
> fix(builder): event information not parsed properly for factory

- .gitmodules
- examples/sample-foundry-project/cannonfile.toml
- packages/builder/src/access-recorder.ts
- packages/builder/src/builder.test.ts
- packages/builder/src/builder.ts
- packages/builder/src/steps/clone.ts
- packages/builder/src/types.test.ts
- packages/builder/src/types.ts
- packages/builder/src/util.test.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/helpers.ts
- packages/website/src/features/Deploy/hooks/useCannonPackage.ts
- packages/website/src/hooks/cannon.ts
should return the signer that will be used if `getDefaultSigner()` is called. Note that this default signer can implicitly be a different signer depending on the txn, so there is no 100% way to reconcile this, but many times, its the same signer no matter the txn (unless explicitly defined otherwise).
if a static deployer is available, it will be supplied as `<%= deployer %>`.
if a static deployer is not available, it is set to undefined.
a bit of research/testing has to be done to determine the consistency of using this field, because, similar to `timestamp`, it can cause cannon package build to be undeterministic/unstable
> add field to get current deployer from inside cannon context

- packages/website/src/features/Packages/interact/useActiveContract.ts
Some packages were not loading the interact tab due to a wrong return type in the useActiveContracts hook.
This hook is supposed to return the active contract to render if the conditions are met, or undefined otherwise. However, it was returning a partially filled object with only the moduleName set but with the contract name and address as undefiend
> fix: CAN-747

- packages/cli/src/commands/verify.ts
- packages/cli/src/util/verify.ts
does the migration to etherscan api v2. Docs on how this works here: https://docs.etherscan.io/etherscan-v2/v2-quickstart#if-youre-coming-from-another-explorer-basescan-arbiscan-polygonscan-etc
also, to prevent from the verification process being insanely long, add a very simple deduplication check that auto-skips contract addresses which have already been seen.
> fix(cli): use etherscan api v2

- packages/website/src/features/Deploy/QueueTransaction.tsx
- packages/website/src/features/Packages/interact/AbiContractMethodInteraction.tsx
- packages/website/src/features/Packages/interact/useContractInteraction.ts
Fixed [CAN-666](https://linear.app/usecannon/issue/CAN-666/suggest-the-user-to-configure-a-custom-rpc-on-the-settings-when-it-is)
Leave yellow color because it looks good.
> fix(website): add custom rpc alert

- packages/builder/src/constants.ts
other RPC endpoints seem to be becoming less reliable
> fix(builder): try using optimism default RPC endpoint
