README.md, packages/cli/src/index.ts, packages/cli/src/rpc.ts
Trying to pass a 'pointer' into the rpc file (`showLogs.rpc`), thought an object would do it? Idk typescript. Otherwise should be all set.
=> Pause anvil logs

packages/cli/src/index.ts, packages/hardhat-cannon/package-lock.json, packages/hardhat-cannon/package.json, packages/hardhat-cannon/src/subtasks/write-deployments.ts, packages/hardhat-cannon/src/tasks/build.ts, packages/hardhat-cannon/src/tasks/publish.ts
Improves CLI + Hardhat plug-in output.
=> Minor UX Improvements

packages/cli/src/util/params.ts, packages/contracts/cannonfile.mintableerc20.toml, packages/contracts/cannonfile.mintableerc721.toml, packages/contracts/hardhat.config.ts, packages/hardhat-cannon/src/index.ts, packages/hardhat-cannon/src/subtasks/load-package-definition.ts, packages/hardhat-cannon/src/task-names.ts, packages/hardhat-cannon/src/tasks/deploy.ts, packages/hardhat-cannon/src/tasks/export.ts, packages/hardhat-cannon/src/tasks/inspect.ts, packages/hardhat-cannon/src/tasks/publish.ts, packages/hardhat-cannon/src/tasks/verify.ts, packages/sample-hardhat-project/cannonfile.toml
fixes a large number of tickets:
https://github.com/usecannon/cannon/issues/61
https://github.com/usecannon/cannon/issues/77
https://github.com/usecannon/cannon/issues/79
https://github.com/usecannon/cannon/issues/80
https://github.com/usecannon/cannon/issues/81
=> hardhat-cannon gotchas and bugs

README.md, packages/website/content/docs-technical.md
=> Fix: typos

packages/builder/src/error/index.ts, packages/cli/src/commands/publish.ts, packages/cli/src/index.ts
the original functionality for reuploading packages for pinning to remote ipfs was not working properly. also, make sure the `force` option works
=> fix recursive upload of packages

packages/cli/src/constants.ts, packages/website/components/search/Cannonfile.vue, packages/website/components/search/Interact.vue, packages/website/components/shared/PackageNetworks.vue
infura-ipfs has been discoverde to be broken. so instead, just use the regular public ipfs server.
=> switch to basic ipfs server

packages/builder/src/ipfs.ts
This resolves an issue present with Node v19
=> ipfs hotfix

packages/builder/src/registry.ts, packages/cli/src/commands/build.ts, packages/cli/src/index.ts
=> better build ux

packages/cli/src/commands/build.ts, packages/cli/src/commands/run.ts, packages/website/package-lock.json
Handles normal output from normal `run` better.
Would like to come up with a better output on the line `Building the chain (ID` that signifies when a fork is being run. Also would be good to have the line after "Checking IPFS for package synthetix-sandbox:latest..." output where it found the package.
=> cli improvements

packages/builder/src/registry.ts, packages/builder/src/steps/contract.test.ts, packages/builder/src/steps/contract.ts, packages/builder/src/steps/import.test.ts, packages/builder/src/steps/import.ts, packages/builder/src/steps/invoke.test.ts, packages/builder/src/steps/provision.test.ts, packages/builder/src/steps/testUtils.ts
add tests to builder module `steps/` files, which were the only files not covered by tests previously in the builder.
This brings our test coverage up to just over 80% for the builder! Next stop, the CLI.
How excited.
=> Steps tests

packages/builder/src/builder.ts, packages/builder/src/package.ts, packages/builder/src/registry.ts, packages/builder/src/steps/invoke.ts, packages/builder/src/steps/provision.ts, packages/cli/src/commands/alter.ts, packages/cli/src/commands/inspect.ts, packages/cli/src/commands/run.ts, packages/website/package-lock.json
was not correctly evaluating preset name due to naive split check
=> fix publish issues

packages/cli/src/commands/setup.ts
Print the current stored config at the beginning of the setup
Exist setup process on the first cancel
Fixed issue on filling registryAddress while the user hasn't entered any
Refs #204
=> Setup exit + bug fix

packages/builder/src/ipfs.ts
Set axios IPFS interaction (read) timeout to 5 minutes
=> IFPS read timeout 5 minutes

packages/cli/src/commands/run.ts, packages/cli/src/index.ts, packages/cli/src/package.ts, packages/cli/src/registry.ts, packages/cli/src/settings.ts
Fixed issue in loading cli setting and suppressing warning messages
Ref #232
=> Fixed cli option loading + suppress warning bug fix

packages/cli/src/commands/build.ts, packages/cli/src/util/printer.ts
=> Printing final publishing messages on build last

packages/cli/bin/cannon.ts, packages/cli/src/index.ts
=> Handle asynchronous commands in cli error handling

packages/cli/src/interact.ts
=> Support falsy values in method arguments

packages/cli/src/commands/build.ts
=> Changed ipfs publish error message

package.json, packages/cli/src/commands/publish.ts, packages/cli/src/index.ts
=> Improve logs on publish

packages/builder/src/runtime.ts, packages/cli/src/commands/build.ts
Update the package fetching log to reflect the loader scheme correctly
Ref #191
=> Update fetching package log

packages/builder/src/definition.ts
load values from settings support in loading default values
Ref #262
=> Settings support in defaultValue

packages/cli/src/commands/run.ts, packages/cli/src/index.ts
=> Fix preset setting in run command

packages/cli/src/loader.test.ts
Fixed issue in loader tests and removed unnecessary mocking
=> loader test fix

packages/cli/src/index.ts
Added verbosity flags for the build command
#289
=> Build command verbosity

packages/builder/src/registry.ts, packages/cli/src/constants.ts
Ref #290 
Changes:
- Changed default provider RPC url
- Added some extra error messages
WIP - Changing the RPC Provider url definitely makes the error less frequent, I did run into the issue once after changing the RPC provider url, however I havent ran into it since so changing the registry had the biggest effect on this issue so far.
=> Txnrevert on geturl

.release-please-manifest.json, release-please-config.json
Need to add these files to the main branch before the release please action can work, as it needs to fetch these files from the main branch to start.
These changes are simply to bootstrap the release please action.
=> bootstrap release please action

package-lock.json, packages/website/package.json, packages/website/src/features/Packages/Function.tsx
Per discussion with @dbeal-eth, we think this might be a better solution than #340. Alternatively, we could add a `createProvider` function to the builder.
=> Use ethers to generate provider

packages/cli/src/commands/build.ts
I have identified that this commit is responsible for the problem https://github.com/usecannon/cannon/commit/f91d19193ac37c2dcd3621c6d12dae6cd8260ad9
=> fix: package version load on build

packages/cli/src/commands/publish.ts, packages/cli/src/index.ts
=> Make chainId required for publish command

packages/cli/src/commands/clean.test.ts
@dbeal-eth  @noahlitvin  This the PR that I was talking in the call
=> Write test cases for cli/commands/clean

packages/website/src/features/Packages/FunctionOutput.tsx
=> fix(website): format tuple array output

.eslintignore, .prettierignore, packages/builder/src/steps/provision.test.ts, packages/builder/src/steps/provision.ts
fixes https://github.com/usecannon/cannon/issues/401
=> fix(builder): provision partial on deploy cancel

packages/website/next.config.js
=> feat(website): include sourcemaps on prod

packages/website/src/features/Packages/CodeExplorer.tsx
=> fix(website): code tab error

packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx, packages/website/src/features/Deploy/QueueTransactionsPage.tsx, packages/website/src/features/Deploy/TransactionDetailsPage.tsx
=> feat(website): add toast on transaction signing

packages/registry/contracts/CannonRegistry.sol, packages/registry/contracts/EfficientStorage.sol, packages/registry/test/contracts/CannonRegistry.test.ts
https://github.com/usecannon/cannon/issues/387
=> feat(fee): Add package publication fee of 1 wei

packages/cli/src/helpers.ts, packages/cli/src/index.ts, packages/cli/src/rpc.ts, packages/cli/src/util/anvil.ts, packages/hardhat-cannon/src/tasks/build.ts, packages/hardhat-cannon/src/tasks/run.ts
Closes https://github.com/usecannon/cannon/issues/369
=> feat(cli): add anvil custom options to run and build commands

packages/builder/src/definition.ts, packages/cli/src/settings.ts
* fix bug in determining
* fix registry priority not being recognized becuause cli settings does
not correctly filter "undefined" options
* (wasnt actually 2.7 regression but) fix issue with resolving correct
layers when multiple inner dependencies exist.
=> fix: 2.7 regressions

packages/website/src/features/Packages/ContractStep.tsx
=> feat(website): sort "highlight" contracts to top of interact tool

packages/cli/src/foundry.ts
leads to problems on etherscan verification/reproduction of correct bytecodes
=> fix(cli): foundry doesn't resolve evm version

packages/website/src/app/packages/[name]/[tag]/[variant]/interact/[moduleName]/[contractName]/[contractAddress]/page.tsx, packages/website/src/features/Packages/Interact.tsx, packages/website/src/features/Packages/InteractPage.tsx, packages/website/src/features/Packages/Tabs/InteractTab.tsx
=> fix(website): fix contract nav highlighting

packages/website/src/lib/builder.ts
Fixing a 500 error here: https://usecannon.com/packages/grateful/latest/10-main/interact
=> fix(website): register run step

packages/website/src/features/GetStarted/RunPackage.tsx
=> docs(website): Update getting started guide

packages/cli/src/commands/clean.test.ts, packages/cli/src/commands/clean.ts
Clearing out all files and folders in tags and metadata_cache. Ensuring their deletion
=> fix(cli): make clean remove all files/folders in tags and metadata_cache

packages/cli/src/commands/interact.ts
Handle runtime error when interacting with cannon package
=> fix(cli): handle interact runtime error

packages/cli/src/commands/fetch.ts, packages/cli/src/constants.ts, packages/cli/src/loader.ts, packages/cli/src/settings.ts
=> feat(cli): use cannon repo

packages/website/src/features/Deploy/PublishUtility.tsx, packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx, packages/website/src/features/Deploy/QueueTransactionsPage.tsx, packages/website/src/features/Deploy/SafeAddressInput.tsx, packages/website/src/features/Settings/SettingsPage.tsx, packages/website/src/helpers/store.ts, packages/website/src/hooks/cannon.ts, packages/website/src/hooks/ipfs.ts
=> fix(website): rename ipfs api url setting + add reset to default settings button

package-lock.json, packages/hardhat-cannon/package.json, packages/website/src/helpers/git.ts, packages/website/src/hooks/git.ts
this should enable support for the synthetix repo for right now
please test prior to merging
=> feat(website): update isomorphic git cors proxy to be under our control

packages/cli/src/commandsConfig.ts, packages/cli/src/index.ts
=> fix(cli): Interact ref bug

.github/dependabot.yml
- Monthly version update check
- Ignore major version bumps
=> chore(deps): ignore major dependabot updates

packages/website/src/features/Search/PackageCard/PackageCard.tsx, packages/website/src/features/Search/PackageCard/PackageCardExpandable.tsx, packages/website/src/features/Search/PackageCard/PackageTable.tsx
=> fix(website): quick explore page refresh

packages/cli/src/loader.ts
even tho we had the cache set up for ipfs, it only caches files which are built locally. for best results, we should also be auto caching any downloaded artifacts (they are pretty small, after all, and lead to massive speed improvement, as well as less thrashing on our servers)
=> feat(cli): cache on repo download

.github/workflows/test-e2e.yml, examples/sample-hardhat-project/package-lock.json, packages/builder/src/steps/contract.ts, packages/cli/test/e2e/e2e-tests.bats, packages/cli/test/e2e/scripts/non-interactive/alter-import-contract.sh, packages/cli/test/e2e/scripts/non-interactive/alter-import-invoke.sh, packages/cli/test/e2e/scripts/non-interactive/fetch.sh
Fixed Alter tests and refactored fetch test. 
Note: 
Noticed today that building the v3 repo fails different locally than on the e2e suite:
Local:
E2E:
=> fix(cli): Fix e2e tests

packages/builder/src/steps/contract.ts
This PR fixes an issue with the build command. It failed when passing arguments like the private key, chain ID, and provider URL. For example, using the command `cannon build mintable-token.permissionless-mint.cannonfile.toml --private-key <your-pk> --chain-id 5 --provider-url https://ethereum-goerli.publicnode.com` resulted in an error.
```
Executing [contract.MintableToken]...
⚠️  Skipping [contract.MintableToken] (TransactionExecutionError: Missing or invalid parameters.
Double check you have provided the correct parameters.
URL: https://ethereum-goerli.publicnode.com
Request body: {"method":"eth_sendTransaction","params":[{"data":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470608060405260405162000d5a38038062000d5a8339810160408190526200002691620001f3565b8282600362000 …
```
=> fix(cli): use `signer.wallet.account` instead of `signer.address` to send transaction

packages/builder/src/types.test.ts, packages/builder/src/types.ts
units were reported missing in the new release
=> fix(builder): missing parseUnits, formatUnits functions

packages/builder/src/registry.test.ts, packages/builder/src/registry.ts
fixes https://linear.app/usecannon/issue/CAN-188
=> fix(cli): fix getUrl function

packages/builder/src/registry.ts, packages/cli/src/util/provider.ts, packages/cli/test/e2e/helpers/bats-helpers.sh, packages/cli/test/e2e/scripts/non-interactive/build-foundry.sh
see individual commits for things that were fixed
=> fix: miscs

packages/cli/src/commands/run.ts
fixes https://linear.app/usecannon/issue/CAN-69
=> fix(cli): Fix logs option on run

packages/builder/src/error/index.ts, packages/builder/src/trace.ts, packages/cli/src/commands/trace.ts
otherwise its possible some calls will not be traced
=> fix(builder): ensure traces work for `estimateContractGas` calls

packages/website/src/features/Packages/Function.tsx
=> fix(website): improve error handling on interact component

packages/website/src/features/Packages/ContractsTable.tsx, packages/website/src/features/Packages/DeploymentExplorer.tsx, packages/website/src/features/Packages/InvokesTable.tsx
CAN-223 + CAN-224
Needs to have the provisioned invokes moved to the function calls table and have the correct contracts have the "highlighted" state
Also, the table component should remove the column for `highlight` if none of the contracts are highlighted.
=> feat(website): deployments UI improvements

packages/builder/src/abis/CannonRegistry.ts, packages/builder/src/abis/Multicall.ts, packages/builder/src/multicall.ts, packages/builder/src/registry.test.ts, packages/builder/src/registry.ts, packages/cli/src/chains.ts, packages/cli/src/helpers.ts
Multicall updates necessary for: https://linear.app/usecannon/issue/CAN-215/deploy-registry
=> fix(registry): update multicall implementation

packages/builder/src/builder.ts, packages/builder/src/steps/clone.test.ts, packages/builder/src/steps/clone.ts
consider that this will update the timestamp, which effects the resulting Qm hash
=> fix(builder): always rerun `clone` to ensure update

packages/website/src/features/Packages/FunctionOutput.tsx
https://github.com/usecannon/cannon/assets/3952453/a51cb4e8-fc27-4765-8404-cf2ed1c8a5f1
=> feat(website): function output tooltip format - 18 decimals

packages/website/src/features/Packages/CodeExplorer.tsx, packages/website/src/features/Packages/Tabs/CodeTab.tsx
The purpose of this PR is to display code from provisioned packages in the Code tab.
https://github.com/usecannon/cannon/assets/3952453/dc71b78a-6679-4cc4-9dff-9960b865e3aa
=> feat(website): provisioned packages code

packages/registry/cannonfile.mainnet.toml, packages/registry/cannonfile.sepolia.toml, packages/registry/cannonfile.toml, packages/registry/contracts/CannonRegistry.sol, packages/registry/test/contracts/CannonRegistry.test.ts
Changes necessary to fix registry deployment on Sepolia + OP Sepolia
=> fix(registry): remove hardcoding of L1 chainId

package-lock.json, packages/builder/src/steps/deploy.ts, packages/cli/package.json, packages/cli/src/commands/interact.ts
previously specifying a value for a payable function leads to incorrect handling of `value` for a transaction, leading to failures.
also fixes `deploy` step to properly handle deploy address when contract has alreayd been deployed.
=> fix(cli): remove `wei` lib dependency, fix interact `value` handle

packages/website/src/features/Packages/Abi.tsx, packages/website/src/features/Packages/Function.tsx
As demonstrated in the video, the UI performance is significantly degraded due to the large number of items being rendered by the ABI component.
https://github.com/usecannon/cannon/assets/3952453/63c70bda-494b-47d6-bbbb-a26db7fb438e
Rendering time without the fix:
With the fix
https://github.com/usecannon/cannon/assets/3952453/70c5718f-71e4-45fe-aff5-342012d0d5a0
Rendering time with the fix:
=> fix(website): abi render collapsed functions

package-lock.json, packages/api/package.json, packages/api/src/config.ts, packages/api/src/errors.ts, packages/api/src/index.ts, packages/api/src/routes/index.ts, packages/api/src/routes/metrics.ts
Implement basic Prometheus metrics on the API using https://www.npmjs.com/package/express-prom-bundle.
=> feat(metrics): basic prometheus metrics

packages/website/src/features/Packages/Abi.tsx, packages/website/src/features/Packages/Function.tsx
This PR fixes the following issues:
- Order functions alphabetically 
- Fix anchor links
- Hide function names
=> fix(website): interact links

packages/website/src/app/layout.tsx
=> feat(website): hide console component

packages/cli/src/constants.ts
=> fix(cli): read from optimism before mainnet

packages/website/src/features/Deploy/NoncePicker.tsx, packages/website/src/features/Deploy/SignTransactionsPage.tsx, packages/website/src/features/Deploy/TransactionDetailsPage.tsx, packages/website/src/hooks/backend.ts, packages/website/src/hooks/safe.ts
https://github.com/usecannon/cannon/assets/3952453/74285fb9-cfc5-4ef4-bd1e-5a63fd3ddf7a
=> fix(website): prevent redirect on tx execution

packages/website/src/features/Deploy/PublishUtility.tsx, packages/website/src/providers/walletProvider.tsx
wasnt able to test because of wallet connect api key thing pain
=> fix(website): try to use providers configured in settings always

packages/website/src/features/Deploy/QueueDrawer.tsx, packages/website/src/features/Deploy/QueueTransaction.tsx, packages/website/src/features/Packages/Function.tsx
The main purpose of this PR is to add a payment input for payable functions.
https://github.com/usecannon/cannon/assets/3952453/e8e9c49f-e54e-46cf-b362-0f8f707b4018
=> feat(website): payable functions - payment input

packages/website/src/hooks/backend.ts
This PR in order to make sure staged and nonce are updated as expected, due to this missing deps already signed wallets were not updating automatically
https://github.com/usecannon/cannon/assets/3952453/10e70cb1-a7c1-4d45-9dd0-c8662fc86c4c
=> fix(website): useSafeTransactions useEffect dependencies

.github/workflows/test-e2e.yml, .github/workflows/test-snx-ci.yml, .github/workflows/test.yml, .github/workflows/verify.yaml, nx.json
=> chore: update nx access token

packages/website/src/hooks/cannon.ts
=> fix(website): scrubbing of transaction hashes

packages/website/src/features/Deploy/DisplayedTransaction.tsx, packages/website/src/features/Deploy/PublishUtility.tsx, packages/website/src/features/Deploy/TransactionDetailsPage.tsx, packages/website/src/features/Deploy/TransactionDisplay.tsx, packages/website/src/hooks/backend.ts, packages/website/src/hooks/cannon.ts, packages/website/src/providers/logsProvider.tsx
https://github.com/usecannon/cannon/assets/3952453/5e2b8359-bb3b-4c3b-91be-932307681510
=> fix(website): performance improvments when rendering txs

packages/website/src/theme/theme.ts
This PR aims to have a standard scroll bar style across multiple browsers
https://github.com/usecannon/cannon/assets/3952453/7f67edc4-4a60-4cdc-9852-2424185fb967
=> fix(website): scroll style

packages/website/src/components/ClientOnly.tsx, packages/website/src/features/Deploy/QueueDrawer.tsx, packages/website/src/pages/deploy/_layout.tsx
This PR aims to fix the following error 
Cause by the "SafeAddressInput" component, it was fixed following this solution: https://www.joshwcomeau.com/react/the-perils-of-rehydration/#abstractions-12
https://github.com/usecannon/cannon/assets/3952453/d6331538-4060-4951-9297-82b218d4410d
=> fix(website): client only wrapper

packages/website/public/_redirects, packages/website/vercel.json
This PR fixes the 404 error on the interact page.
=> fix(website): interact page rewrites

packages/cli/src/commands/publish.ts, packages/cli/src/commands/unpublish.ts, packages/cli/src/index.ts, packages/cli/src/registry.ts
Fixes a bug where sometimes it wasn't able to find local images, because it was wrongly comparing number with string:
=> fix(publish): lookup of local packages

packages/website/src/features/Deploy/SimulateTransactionButton.tsx, packages/website/src/features/Deploy/TransactionDetailsPage.tsx, packages/website/src/helpers/safe.ts, packages/website/src/hooks/backend.ts
[Screencast from 2024-06-05 20-33-46.webm](https://github.com/usecannon/cannon/assets/3952453/9198a6b9-f7dd-45d6-8c0a-9eda569b3d56)
=> fix(website): tenderly simulation button

packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx, packages/website/src/features/Deploy/TransactionDetailsPage.tsx
[Screencast from 2024-06-07 09-37-41.webm](https://github.com/usecannon/cannon/assets/3952453/cfd345a9-8013-4ae6-93d2-4b75dbcca397)
=> fix(website): offer to connect/switch to sign txn

packages/website/src/features/Deploy/TransactionDetailsPage.tsx
This PR an small issue where the sign button was not signing the transaction but switching the network only
=> fix(website): sign button does not sign the transaction

packages/cli/src/commands/build.ts, packages/cli/src/commandsConfig.ts, packages/cli/src/util/build.ts, packages/cli/src/write-script/render-ethers.ts, packages/cli/src/write-script/render-json.ts, packages/cli/src/write-script/stream-steps.ts, packages/cli/src/write-script/types.ts, packages/cli/src/write-script/write.ts, packages/hardhat-cannon/src/tasks/build.ts
=> chore(writeScript): Revert "chore(writeScript): remove --write-script experimental feature"

packages/website/src/features/Packages/DeploymentExplorer.tsx, packages/website/src/pages/packages/[name]/[tag]/[variant]/_layout.tsx
We can't safely get this working due to same origin policy afaik
=> feat(website): Hide interact tab for local packages

packages/builder/src/access-recorder.ts, packages/builder/src/builder.ts, packages/builder/src/runtime.ts
quite a few misc fixes in here:
* add timestamp and block number info to more places
* fix(builder): all artifacts for trace 
* fix access recorder not properly resolving with steps that have logic
* better stack tracing
* better printing out of step name prior to printing out errors
=> fix(builder): misc

examples/router-architecture/cannonfile.toml, packages/builder/src/schemas.ts, packages/builder/src/steps/router.ts
Closes https://linear.app/usecannon/issue/CAN-404/add-highlight-to-router
=> fix(router): add router highlight

packages/cli/src/commands/build.ts, packages/cli/src/commands/run.ts, packages/cli/src/helpers.test.ts, packages/cli/src/write-script/types.ts
@noisekit PR https://github.com/usecannon/cannon/pull/1293 with some extra fixes and CI enabled.
=> fix: Invalid import references (#1293)

packages/website/src/features/Packages/Interact.tsx, packages/website/src/features/Packages/PackagePage.tsx, packages/website/src/features/Packages/Tabs/InteractTab.tsx, packages/website/src/hooks/routing/usePackageUrlParams.ts, packages/website/src/hooks/routing/usePackageVersionUrlParams.ts, packages/website/src/pages/404.tsx, packages/website/src/pages/packages/[name]/[tag]/[variant]/_layout.tsx, packages/website/src/pages/packages/[name]/[tag]/[variant]/interact/index.tsx, packages/website/src/pages/packages/[name]/index.tsx
Closes CAN-436.
Add a 404 page when navigating to a unknown page, for example `/package/dontExists`
=> feat(website): CAN-436 - Package not found

packages/builder/src/access-recorder.ts, packages/builder/src/definition.ts, packages/builder/src/steps/var.ts, packages/cli/src/commands/inspect.ts
Just some random types fixes that helped me debug stuff.
=> chore(builder): fix misc types

packages/website/src/features/Deploy/TransactionDetailsPage.tsx, packages/website/src/hooks/registry.ts, packages/website/src/pages/deploy/txn/[chainId]/[safeAddress]/[nonce]/[sigHash]/index.tsx
This PR fixes the rendering of already executed TXs
=> fix(website): rendering of TX

.github/workflows/test-snx-ci.yml, packages/cli/test/e2e/scripts/non-interactive/downstream-ci-synthetix-v3.sh, packages/cli/test/e2e/synthetix-ci.bats
fixes https://linear.app/usecannon/issue/CAN-456/test-snx-ci-job-is-not-working
=> chore: fix snx ci

README.md
Add dependabot config recommendation to readme
=> chore: Add dependabot config recommendation to readme

packages/builder/src/steps/invoke.ts
fixes https://linear.app/usecannon/issue/CAN-485/on-[deploy]-step-be-able-to-specify-abiof-and-artifact-at-the-same
=> fix(builder): when specifying artifact and abiOf, prioritize abiOf

packages/website/src/features/Deploy/DisplayedTransaction.tsx, packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx, packages/website/src/features/Deploy/TransactionDetailsPage.tsx
needs to be tested briefly... what was our test txn strategy for gitops?
=> fix(website): misc

packages/website/src/helpers/rpc.ts, packages/website/src/hooks/cannon.ts, packages/website/src/hooks/fork.ts, packages/website/src/providers/CannonProvidersProvider.tsx, packages/website/src/providers/CannonRegistryProvider.tsx
#CAN-514.
Adding changes coming from https://github.com/usecannon/cannon/pull/1330
=> feat(website): use custom providers when forking

packages/website/src/features/Deploy/PublishUtility.tsx, packages/website/src/features/Deploy/TransactionDetailsPage.tsx
Closes https://linear.app/usecannon/issue/CAN-517/publish-package-section-is-not-being-shown-on-tx-page
=> fix(website): publish box render

packages/website/src/features/Packages/Tabs/InteractTab.tsx
https://github.com/user-attachments/assets/38fd648e-46b3-4df0-b9a0-8d0aad54a28b
fixes https://linear.app/usecannon/issue/CAN-490/sort-contracts-in-interact-page-alphabetically
=> fix(website): Sorting contracts in interact page alphabetically

.github/workflows/check-branch-name.yml
Closes https://linear.app/usecannon/issue/CAN-534/enforce-branch-names
=> chore: add branch name validations

packages/builder/src/package.ts
Backmerge of fix from https://github.com/usecannon/cannon/pull/1408
=> fix(publish): chain id setup backmerge

packages/cli/src/commands/build.ts
=> fix(cli): add private source code notice

packages/cli/src/commands/alter.test.ts, packages/cli/src/commands/alter.ts, packages/cli/src/commands/build.ts, packages/cli/src/commands/config/index.ts, packages/cli/src/commands/decode.ts, packages/cli/src/commands/diff.ts, packages/cli/src/commands/inspect.test.ts, packages/cli/src/commands/inspect.ts, packages/cli/src/commands/publish.test.ts, packages/cli/src/commands/publish.ts, packages/cli/src/commands/run.ts, packages/cli/src/commands/trace.ts, packages/cli/src/commands/verify.ts, packages/cli/src/index.ts, packages/cli/src/util/build.ts, packages/hardhat-cannon/src/internal/cannon.ts, packages/hardhat-cannon/src/tasks/alter.ts, packages/hardhat-cannon/src/tasks/build.ts, packages/hardhat-cannon/src/tasks/inspect.ts, packages/hardhat-cannon/src/tasks/test.ts
Closes https://linear.app/usecannon/issue/CAN-532/remove-preset-param-everywhere
=> chore(cli): remove `--preset` flag

packages/website/src/features/Settings/CustomProviders.tsx, packages/website/src/features/Settings/SafeTransactionService.tsx, packages/website/src/features/Settings/SettingsPage.tsx
Fix: remove trailing slash if present when a safe tx service url is entered.
Feat: add URL validation  in safe tx service url input.
Refactor: Move Safe tx URL to a new file.
=> fix(website): CAN-540 safe tx service input.

packages/repo/package.json, packages/repo/test/fixtures/QmYrLsLZwGGg68XwGkdrx8q9KaRSHq7e5sa6PbT7kNXjKw.json, packages/repo/test/fixtures/Qmb276cgTKrZULAR1RUUuXBAzFASkCMXLXaWodtb6LxMVZ.json, packages/repo/test/helpers/ipfs-server-mock.ts, packages/repo/test/helpers/redis-server-mock.ts, packages/repo/test/helpers/repo-server.ts, packages/repo/test/helpers/spawn.ts, packages/repo/test/index.test.ts, packages/repo/tsconfig.json, pnpm-lock.yaml
Add some test cases for /repo package, with all the necessary mock servers running.
=> test(repo): add tests for repo package

packages/website/src/features/Packages/FunctionOutput.tsx
This PR fixes an issue in Interact where we were not displaying the full array values.
=> fix(website): handle array values in interact

packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx, packages/website/src/hooks/cannon.ts
Remove deployTxHash in build step
=> fix(website): CAN-602

packages/website/src/features/Packages/FunctionOutput.tsx
Fixes the rendering of Arrays with no value interact page.
=> fix(interact): rendering arrays with no result

packages/website/src/features/Docs/DocsCannonfilesPage.tsx
- Fix anchor links in learn/cannonfiles.
- replace <code> with <CodeBlock />
=> fix(website): CAN-618

packages/website/src/components/CustomSpinner.tsx, packages/website/src/components/PageLoading.tsx, packages/website/src/features/Docs/DocsLandingPage.tsx, packages/website/src/pages/learn/_layout.tsx, packages/website/src/pages/learn/cannonfile/index.tsx, packages/website/src/pages/learn/cli/index.tsx, packages/website/src/pages/learn/guides/get-started/index.tsx, packages/website/src/pages/learn/index.tsx, packages/website/src/providers/CannonProvidersProvider.tsx
- Center loaders
- Did some modifications to see if the error when navigating to learn/cannonfile is fixes
=> fix(website): CAN-617

packages/website/src/features/Deploy/TransactionDetailsPage.tsx
temp fix ahead of redesign of this section
=> fix(website): max right sidebar width on large displays in transaction details page

packages/builder/package.json, packages/builder/src/definition.ts, packages/builder/src/steps/router.ts, pnpm-lock.yaml
prevent router from being redeployed unnecessarily
also update router to not be so huge when deployed on chain
also fix so that chain definition will stable sort objects so we can hash them safely
=> fix(builder): router various issues

packages/builder/src/actions.ts, packages/builder/src/builder.test.ts, packages/builder/src/builder.ts, packages/builder/src/definition.test.ts, packages/builder/src/definition.ts, packages/builder/src/package-reference.ts, packages/builder/src/steps/clone.ts, packages/builder/src/util.test.ts, packages/builder/src/util.ts
prevents unnecessary errors in certain circumstances, paves the way for smart toml file language server features.
=> fix(builder): reduce the amount of checks that happen by default on chain definition

packages/website/guides/build-with-cannon.mdx, packages/website/guides/create-a-project.mdx, packages/website/guides/deploy-onchain.mdx, packages/website/guides/publish.mdx, packages/website/guides/setup.mdx
I did a pass afterwards and they seem pretty good changes to me, but please validate me.
=> fix(website): update guides with AI assisted improvements

packages/website/src/components/ClipboardButton.tsx, packages/website/src/features/Deploy/DisplayedTransaction.tsx
Added the clipboard component
Had the 0x0000... hash if the item is empty
=> fix(website): copy button component

packages/cli/src/rpc.ts, packages/cli/src/util/on-keypress.ts, packages/registry/package.json, packages/registry/scripts/list-packages.ts, pnpm-lock.yaml
This PR does not change any critical part, just updates the `script/list-packages` script used to list all the published packages directly from the registry events.
=> fix(registry): fix list packages script

packages/cli/src/commands/config/index.ts, packages/cli/src/commands/inspect.test.ts, packages/cli/src/commands/inspect.ts, packages/cli/src/index.ts
This PR:
1. Fixes the default value for the `--out` param
2. Fixes the `--json` param
3. Updates the docs for the possible values
4. Adds some extra validations to it
=> fix(cli): default value for --out param

packages/website/next-env.d.ts, packages/website/src/features/GetStarted/SetupSection/FoundryGuide/CreateCannonFile.tsx, packages/website/src/features/GetStarted/SetupSection/FoundryGuide/ImportProvisionPackages.tsx, packages/website/src/features/GetStarted/SetupSection/FoundryGuide/TestYourProtocol.tsx, packages/website/src/features/GetStarted/SetupSection/HardhatGuide/CreateCannonFile.tsx, packages/website/src/features/GetStarted/SetupSection/HardhatGuide/ImportProvisionPackages.tsx, packages/website/src/features/GetStarted/SetupSection/HardhatGuide/TestYourProtocol.tsx, packages/website/src/features/Packages/PackageAccordionHelper/IntegrateWithPackage.tsx, packages/website/src/features/Router/RouterPage.tsx
=> fix(website): use snippet instead of codepreview in docs

packages/website/src/features/Packages/FunctionOutput.tsx
Fixed [CAN-681](https://linear.app/usecannon/issue/CAN-681/nested-tuples-still-have-trouble-in-interact-tool-output#comment-faec4b64).
And all outputs are displayed.
=> fix(website): nested tuples issues

packages/website/src/features/Packages/FunctionOutput.tsx
closes #CAN-692.
Interact for Array values
=> fix(website): CAN-692. 

packages/website/src/components/CommandPreview.tsx
Matches to the theme of the shiki component
=> fix(website): commandpreview bg color

packages/website/src/components/AbiParameterPreview.tsx, packages/website/src/components/ClipboardButton.tsx, packages/website/src/components/ExternalLinkButton.tsx, packages/website/src/features/Deploy/DisplayedTransaction.tsx, packages/website/src/features/Packages/Function.tsx, packages/website/src/features/Packages/FunctionOutput.tsx, packages/website/src/features/Packages/Interact.tsx
=> feat(website): add etherscan external link when address input types

packages/website/src/components/AbiParameterPreview/utils/index.test.ts, packages/website/src/components/AbiParameterPreview/utils/index.ts, packages/website/src/features/Packages/FunctionOutput.test.tsx, packages/website/src/features/Packages/FunctionOutput.tsx
Closes #701.
Fix the call function on the interact section when there is only 1 function parameter.
=> fix(website): Interact single values

packages/website/src/features/Packages/PackageByNamePage.tsx, packages/website/src/features/Packages/VersionSelect.tsx
Disable error handling so it doesn't crash the page.
=> fix(website): page crash

packages/website/src/features/Packages/FunctionOutput.tsx
Closes #CAN-704
Interact section bug
=> fix(website): CAN-704 -- hotfix

packages/website/src/features/Deploy/QueueFromGitOpsPage.tsx
might fix an issue from client
=> fix safe chainid

packages/website/serve.json, packages/website/vercel.json
=> fix(website): direct routing to /somePackage/deployments/:section

packages/website/src/providers/CannonProvidersProvider.tsx
until it gets added to viem, just putting it here
=> feat(website): polynomial chain

packages/website/src/components/ClipboardButton.tsx, packages/website/src/components/ExternalLinkButton.tsx, packages/website/src/components/NavLink.tsx, packages/website/src/components/SearchInput.tsx, packages/website/src/features/Deploy/QueueDrawer.tsx, packages/website/src/features/Deploy/SafeAddressInput.tsx, packages/website/src/features/Packages/Abi.tsx, packages/website/src/features/Packages/CannonfileExplorer.tsx, packages/website/src/features/Packages/DeploymentExplorer.tsx, packages/website/src/features/Packages/Function.tsx, packages/website/src/features/Packages/FunctionInput/AddressInput.tsx, packages/website/src/features/Packages/FunctionInput/BoolInput.tsx, packages/website/src/features/Packages/FunctionInput/ByteInput.tsx, packages/website/src/features/Packages/FunctionInput/DefaultInput.tsx, packages/website/src/features/Packages/FunctionInput/JsonInput.tsx, packages/website/src/features/Packages/FunctionInput/NumberInput.tsx, packages/website/src/features/Packages/Interact.tsx, packages/website/src/features/Search/PackageCard/PackageCardExpandable.tsx, packages/website/src/pages/packages/[name]/[tag]/[variant]/NameTagVariantLayout.tsx
Added "data-testid" for e2e test
=> fix(website): add data-testid

packages/website/src/features/Packages/DeploymentExplorer.tsx
=> fix(website): package.contracts

packages/website/src/components/AbiParameterPreview/index.tsx, packages/website/src/components/AbiParameterPreview/utils/index.test.ts, packages/website/src/components/AbiParameterPreview/utils/index.ts, packages/website/src/features/Packages/Function.tsx, packages/website/src/features/Packages/FunctionInput.tsx, packages/website/src/features/Packages/FunctionOutput.test.tsx, packages/website/src/features/Packages/FunctionOutput.tsx
=> fix(website): interact

packages/website/src/features/Deploy/SimulateSafeTx.tsx, packages/website/src/features/Deploy/SimulateTransactionButton.tsx, packages/website/src/features/Settings/SettingsPage.tsx
=> feat(website): verify tx notice

packages/website/cypress/integration/Interact.feature
Fix the error displayed on interact
=> fix(website): e2e interact test case

.github/workflows/upload-to-ipfs.yml, package.json
Github action to upload website build to IPFS
=> chore(website): upload to ipfs

packages/builder/src/schemas.ts
its going to be validated by the `PackageReference` check anyway and may be interpolated.
=> remove unnecessary schema checks for length too long

packages/website/src/hooks/backend.ts
better user signing experience, and allegedly more secure
need to test with an actual ledger just to make sure, sometimes its stupid
=> enable signing via type signatures

packages/website/cypress/integration/Interact.feature, packages/website/src/features/Packages/Function.tsx
fixed bool output on interact
Also fixed e2e test cases
=> fix(website): interact output

.github/workflows/bump-viem.yml
fixes https://linear.app/usecannon/issue/CAN-725/add-github-action-for-easily-updating-viem
=> add bump viem job

packages/website/cypress/integration/Interact.feature
adjust e2e interact test cases
=> fix(website): adjust e2e interact

packages/website/src/components/SearchInput.tsx, packages/website/src/features/Packages/interact/ContractsList.tsx, packages/website/src/features/Packages/interact/Interact.tsx
Fixed [CAN-729](https://linear.app/usecannon/issue/CAN-729/search-filter-for-contracts-on-website-is-flawed).
When hitting the enter key in the searchbar, the first contract of lists is selected.
=> fix(website): fix interact serachbar

packages/cli/src/write-script/render-cast.ts, packages/cli/src/write-script/write.ts
implementation is there ,just need to add it to the list of valid dump formats.
=> add missing write script format `cast`

.github/workflows/upload-to-ipfs.yml
Fix GH IPFS upload, to upload out folder instead of package/website/out
=> fix(ghAction): ipfs upload out folder

packages/website/src/features/Packages/interact/useActiveContract.ts
=> fix(website): CAN-748

packages/website/src/features/Packages/Function.tsx, packages/website/src/helpers/ethereum.ts, packages/website/src/hooks/ethereum.ts
Also send value for walletClient.sendTransaction
=> hotfix(website): contractTransaction

packages/website/src/components/ClipboardButton.tsx, packages/website/src/features/Search/PackageCard/DataTable.tsx, pnpm-lock.yaml
Adjust clipboard copy icon ([CAN-752](https://linear.app/usecannon/issue/CAN-752/adjust-copy-icon)).
=> fix(website): adjust clipboard icon

packages/website/src/features/Settings/CopySettingButton.tsx, packages/website/src/features/Settings/CustomProviders.tsx, packages/website/src/features/Settings/CustomSafeTxServices.tsx, packages/website/src/features/Settings/ImportSettingDialog.tsx, packages/website/src/features/Settings/SafeTransactionService.tsx, packages/website/src/features/Settings/SettingResetButton.tsx, packages/website/src/features/Settings/SettingsPage.tsx
Add new features by following [CAN-741](https://linear.app/usecannon/issue/CAN-741/add-some-sort-of-a-capability-to-copy-settings-with-one-click)
- Copy Setting
- Edit Settings
=> fix(website): copy and import settings

packages/website/src/helpers/store.ts
=> feat(website): setup default otterscan url
